import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { contentEditorSlug, contentWordCount, escapeHtml, filterRows, normalizeTags, routeFromHash, sitePublicPath, statusClass } from '../assets/js/utils.mjs'

test('routeFromHash parses admin routes safely', () => {
  assert.equal(routeFromHash('#/admin'), 'dashboard')
  assert.equal(routeFromHash('#/admin/languages?enabled=1'), 'languages')
  assert.equal(routeFromHash('#/unknown'), 'dashboard')
})

test('statusClass maps semantic statuses', () => {
  assert.equal(statusClass('发布失败'), 'badge-red')
  assert.equal(statusClass('待审核'), 'badge-amber')
  assert.equal(statusClass('已发布'), 'badge-green')
})

test('filterRows searches all visible fields and filters status', () => {
  const rows = [{ id: 1, name: '德国站', status: '运行中' }, { id: 2, name: '法国站', status: '维护中' }]
  assert.equal(filterRows(rows, '德国', '全部站点').length, 1)
  assert.equal(filterRows(rows, '', '维护中').length, 1)
})

test('escapeHtml prevents executable markup injection', () => {
  assert.equal(escapeHtml('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;')
})

test('normalizeTags accepts Chinese commas, removes duplicates and enforces limit', () => {
  assert.deepEqual(normalizeTags('物流, 欧洲专线，物流\n门到门'), ['物流', '欧洲专线', '门到门'])
  assert.deepEqual(normalizeTags('A,a,B', 2), ['A', 'B'])
})

test('dialog close and cancel actions bypass required-field validation', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  assert.match(html, /formnovalidate value="cancel" aria-label="关闭"/)
  assert.match(html, /formnovalidate value="cancel">取消<\/button>/)
})

test('content editor creates safe deterministic slugs', () => {
  assert.equal(contentEditorSlug('  Global_Logistics / SEO Guide  '), 'global-logistics/seo-guide')
  assert.equal(contentEditorSlug('中文标题', new Date('2026-08-27T00:00:00Z')), 'article-20260827')
})

test('content editor counts CJK characters and latin words', () => {
  assert.equal(contentWordCount('多语言 SEO helps global logistics'), 7)
  assert.equal(contentWordCount('  '), 0)
})

test('independent language sites use clean root paths', () => {
  assert.equal(sitePublicPath({ language_count: 1 }, 'it-IT', 'guide/spedizioni-internazionali'), '/guide/spedizioni-internazionali')
  assert.equal(sitePublicPath({ language_count: 1 }, 'de-DE'), '/')
  assert.equal(sitePublicPath({ language_count: 2 }, 'de-DE', 'ratgeber/logistik'), '/de-DE/ratgeber/logistik')
})

test('content editor route keeps its essential authoring and publishing controls', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(html, /id="content-editor-view"/)
  assert.match(app, /id="content-editor-form"/)
  assert.match(app, /data-rich-editor/)
  assert.match(app, /data-content-action="save"/)
  assert.match(app, /data-content-action="review"/)
  assert.match(app, /data-content-action="publish"/)
  assert.match(app, /Google SEO 设置/)
  assert.match(app, /name="cover_media_id"/)
  assert.match(app, /data-media-target.*content-cover|openMediaUploadDialog\('content-cover'\)/)
  assert.match(app, /cover_media_id:/)
})

test('product gallery copies selected files before resetting the file input', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /const files = Array\.from\(input\.files \|\| \[\]\); input\.value = ''; void uploadProductGalleryFiles\(form, files\)/)
  assert.match(app, /data-gallery-input/)
  assert.match(app, /data-gallery-upload/)
  assert.match(app, /data-gallery-prev/)
  assert.match(app, /data-gallery-next/)
  assert.match(app, /function scrollProductGallery\(/)
  assert.match(app, /clipboard\?\.items[\s\S]*?getAsFile/)
  assert.match(app, /Cancelling the native picker|取消.*FileList/)
  assert.match(app, /loading="lazy" decoding="async" width="78" height="78"/)
  assert.match(css, /\.product-gallery-carousel/)
  assert.match(css, /\.product-gallery-item img[^}]*aspect-ratio: 1/)
  assert.match(css, /\.product-gallery-item img[^}]*height: var\(--product-gallery-thumb-size\)/)
  assert.match(css, /--product-gallery-thumb-size: 78px/)
  assert.match(css, /\.product-gallery-grid[^}]*overflow-x: auto/)
})

test('metafields are top-level and product editor persists scoped values', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(html, /data-route="metafields"/)
  assert.match(app, /content-metafields-panel/)
  assert.match(app, /GET \/api\/v1\/metafields|\/api\/v1\/metafields\?owner_type=/)
  assert.match(app, /\/api\/v1\/metafields\/values/)
  assert.match(app, /metafieldOwnerTypeForContent/)
  assert.match(app, /richtext: '富文本'/)
  assert.match(app, /function metafieldRichEditorMarkup\(/)
  assert.match(app, /data-metafield-rich-editor-content/)
  assert.match(app, /data-metafield-rich-source/)
  assert.match(app, /function runMetafieldRichCommand\(/)
  assert.match(app, /function handleMetafieldRichPaste\(/)
  assert.match(app, /data-metafield-rich-image-input/)
  assert.match(app, /data-metafield-rich-command\], \[data-metafield-rich-block\]/)
  assert.match(app, /validateContentMetafields\(form\)/)
})

test('content editor uploads and localizes pasted images instead of prompting for remote URLs', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(app, /data-rich-image-input/)
  assert.match(app, /contentEditorView\.addEventListener\('paste'/)
  assert.match(app, /clipboard\.items/)
  assert.match(app, /\/api\/v1\/media\/upload/)
  assert.match(app, /\/api\/v1\/media\/import/)
  assert.match(app, /正在本地化/)
  assert.doesNotMatch(app, /输入图片地址；正式使用时建议从媒体中心选择/)
})

test('content editor includes heading four and SEO AI fallback controls', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(app, /<option value="h4">标题 4<\/option>/)
  assert.match(app, /data-content-action="seo-extract"/)
  assert.match(app, /\/api\/v1\/content\/seo-suggestions/)
  assert.match(app, /applyLocalSEODefaults/)
})

test('content editor previews generated JSON-LD without replacing the page entity', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /function structuredDataPreviewMarkup\(\)/)
  assert.match(app, /data-schema-preview/)
  assert.match(app, /function updateStructuredDataPreview\(form\)/)
  assert.match(app, /恢复系统自动生成的结构化数据/)
  assert.match(app, /mergeStructuredPreview\(document, custom\)/)
  assert.match(app, /type === 'organization' && document\.publisher/)
  assert.match(app, /type === 'website' && document\.isPartOf/)
  assert.match(app, /type === 'breadcrumblist' && document\.breadcrumb/)
  assert.match(css, /\.schema-preview-summary/)
  assert.match(css, /\.schema-preview-code/)
})

test('structured data preview can copy its canonical JSON-LD on local HTTP', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /data-content-action="structured-copy"/)
  assert.match(app, /async function copyTextToClipboard\(value\)/)
  assert.match(app, /navigator\.clipboard\?\.writeText/)
  assert.match(app, /document\.execCommand\('copy'\)/)
  assert.match(app, /最终 JSON-LD 已复制到剪贴板/)
  assert.match(css, /\.schema-preview-actions/)
})

test('new content defaults publishing time to the current local time without overwriting existing content', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(app, /function defaultContentScheduledAt\(item, creating = false\)/)
  assert.match(app, /const scheduledAt = defaultContentScheduledAt\(item, mode !== 'edit'\)/)
  assert.match(app, /默认当前时间；改为未来时间并发布后/)
})

test('content editor commits typed tags on delimiter, blur and save', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(app, /function commitPendingContentTag\(form\)/)
  assert.match(app, /addContentTag\(form, entry\.value\)/)
  assert.match(app, /contentEditorView\.addEventListener\('focusout'/)
  assert.match(app, /commitPendingContentTag\(form\)/)
  assert.match(app, /输入标签后按回车或逗号/)
  assert.match(app, /离开输入框或保存时自动创建/)
  assert.match(app, /function contentTagHelpText\(count\)/)
  assert.match(app, /event\.target\.matches\('\[data-tag-entry\]'\) && !event\.isComposing && \/\[,，\]\//)
})

test('taxonomy is real data and content editor reuses scoped category and tag suggestions', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const data = readFileSync(new URL('../assets/js/data.mjs', import.meta.url), 'utf8')
  assert.match(app, /fetchJSON\(siteScopedAPIPath\('\/api\/v1\/taxonomy\/terms'\)\)/)
  assert.match(app, /content-category-suggestions/)
  assert.match(app, /content-tag-suggestions/)
  assert.match(app, /refreshContentTaxonomySuggestions/)
  assert.match(app, /保存时自动创建/)
  assert.match(data, /taxonomy:\s*\{[\s\S]*?rows: \[\]/)
})

test('top site switcher scopes operational modules and refreshes their cached data', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /const siteScopedRoutes = new Set\(\['content', 'taxonomy', 'urls', 'publishing', 'localization'\]\)/)
  assert.match(app, /siteScopedAPIPath\(contentPath\)/)
  assert.match(app, /content_type=page/)
  assert.match(app, /siteScopedAPIPath\('\/api\/v1\/taxonomy\/terms'\)/)
  assert.match(app, /siteScopedAPIPath\('\/api\/v1\/urls\/redirects'\)/)
  assert.match(app, /siteScopedAPIPath\('\/api\/v1\/publishing\/releases'\)/)
  assert.match(app, /siteScopedAPIPath\('\/api\/v1\/localization\/jobs'\)/)
  assert.match(app, /for \(const route of siteScopedRoutes\)/)
  assert.match(app, /moduleState\.selected\.clear\(\)/)
  assert.match(app, /await loadRoute\('sites'\)/)
  assert.match(app, /role="menuitemradio" aria-checked="false"/)
  assert.match(app, /当前站点：/)
  assert.match(css, /\.site-menu button\[aria-checked="true"\]/)
})

test('content management can show every authorized site without changing the active publishing site', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const data = readFileSync(new URL('../assets/js/data.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /contentScope: 'all'/)
  assert.match(app, /function isAllSitesContentScope\(\)/)
  assert.match(app, /function renderContentScopePicker\(\)/)
  assert.match(app, /data-content-scope/)
  assert.match(app, /所有可访问站点/)
  assert.match(app, /isAllSitesContentScope\(\) \? contentPath : siteScopedAPIPath\(contentPath\)/)
  assert.match(app, /site: item\.site_name \|\| `站点 #\$\{item\.site_id\}`/)
  assert.match(app, /moduleState\.selected\.clear\(\)[\s\S]*?loadRoute\('content', true\)/)
  assert.match(data, /content:\s*\{[\s\S]*?key: 'site', label: '所属站点'/)
  assert.match(css, /\.content-scope-picker/)
})

test('traffic analytics keeps real data controls while using the compact dashboard layout', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /\/api\/v1\/analytics\/overview\?site_id=/)
  assert.match(app, /data-analytics-export/)
  assert.match(app, /data-analytics-refresh/)
  assert.match(app, /data-analytics-days=/)
  assert.match(app, /data-analytics-custom-range/)
  assert.match(app, /analytics-main-column/)
  assert.match(app, /analytics-side-rail/)
  assert.match(app, /analyticsTrendSVG/)
  assert.match(app, /moduleState\.analyticsSiteID = Number\(button\.dataset\.siteId \|\| 0\)[\s\S]*?loadRoute\('analytics', true\)/)
  assert.match(css, /\.analytics-grid \{ display: grid; grid-template-columns: minmax\(0, 1fr\) 322px;/)
  assert.match(css, /\.analytics-lower-grid \{ display: grid;/)
  assert.match(css, /\.analytics-side-rail \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\);/)
})

test('AI localization uses published English as source and only creates AI drafts for active template-bound sites', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const data = readFileSync(new URL('../assets/js/data.mjs', import.meta.url), 'utf8')
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  assert.match(html, /id="localization-dialog"/)
  assert.match(app, /defaultEnglishSite/)
  assert.match(app, /item\.status !== 'published'/)
  assert.match(app, /\/localization-options/)
  assert.match(app, /\/localize`/)
  assert.match(app, /scope: 'full', overwrite: false/)
  assert.match(app, /不会自动发布/)
  assert.match(app, /target\.existing/)
  assert.match(app, /target\.template_bound/)
  assert.match(app, /target\.site_online/)
  assert.match(app, /target\.template_online/)
  assert.match(app, /同步到已上线分站/)
  assert.match(app, /locked_terms/)
  assert.match(app, /forbidden_terms/)
  assert.match(data, /以英语为源内容/)
})

test('content revisions support field comparison and safe restore as a new draft', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /data-content-action="revisions"/)
  assert.match(app, /function revisionDiffMarkup/)
  assert.match(app, /data-revision-restore/)
  assert.match(app, /\/revisions\/\$\{encodeURIComponent\(revisionID\)\}\/restore/)
  assert.match(app, /新的草稿版本/)
  assert.match(css, /\.revision-diff-list/)
})

test('global search hides quick actions outside the current RBAC permissions', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const data = readFileSync(new URL('../assets/js/data.mjs', import.meta.url), 'utf8')
  assert.match(app, /quickActions\.filter\(\(item\) => can\(item\.permission\)/)
  assert.match(data, /permission: 'content\.write'/)
  assert.match(data, /permission: 'jobs\.manage'/)
})

test('site and content lists expose explicit row actions and bulk deletion controls', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /data-site-edit/)
  assert.match(app, /data-site-delete/)
  assert.match(app, /data-bulk-delete-sites/)
  assert.match(app, /data-content-edit/)
  assert.match(app, /data-content-view/)
	assert.match(app, /\/admin\/content-preview\//)
	assert.match(app, /在新窗口使用前端模板安全预览/)
  assert.match(app, /data-content-delete/)
  assert.match(app, /data-content-bulk-select/)
  assert.match(app, /批量操作/)
  assert.match(app, /data-bulk-delete-contents/)
  assert.match(app, /data-bulk-update-status/)
  assert.match(app, /data-bulk-update-category/)
  assert.match(app, /\/api\/v1\/contents\/bulk-update/)
  assert.match(app, /\/api\/v1\/contents\/bulk-delete/)
  assert.match(app, /正在批量删除/)
  assert.match(app, /contentBulkSelectionLimit = 100/)
  assert.match(app, /请选择先勾选内容|请先勾选内容/)
  assert.match(app, /任一版本冲突时整批回滚/)
  assert.match(app, /删除内容组会同时移除其全部站点 \/ 语言版本/)
  assert.match(app, /content-readonly-frame/)
  assert.match(app, /sitePreviewURL/)
  assert.match(app, /row-action-edit/)
  assert.match(app, /row-action-preview/)
  assert.match(app, /i-edit|icon\('edit'/)
  assert.match(app, /i-eye|icon\('eye'/)
  assert.match(app, /i-trash|icon\('trash'/)
  assert.match(app, /安全停用站点并保留内容与审计数据/)
  assert.match(css, /\.row-actions/)
  assert.match(css, /font-family: inherit/)
  assert.match(css, /\.row-action-button \.icon/)
  assert.match(css, /\.bulk-action-bar/)
})

test('published content links to the native multilingual frontend', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(app, /function contentFrontendPreviewURL/)
  assert.match(app, /function isScheduledContent/)
  assert.match(app, /打开前台页面/)
  assert.match(app, /item\.status === 'published'/)
  assert.match(app, /最多受 60 秒页面缓存影响/)
})

test('public template renders six-language SEO pages and CMS content', () => {
  const page = readFileSync(new URL('../public.html', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/public.css', import.meta.url), 'utf8')
  assert.match(page, /hreflang/)
  assert.match(page, /application\/ld\+json/)
  assert.match(page, /\.Content\.Body/)
  assert.match(page, /\.Published/)
	assert.match(page, /article-masthead/)
	assert.match(page, /\.Content\.ReadingMinutes/)
	assert.match(page, /\.Related/)
  assert.match(page, /language-picker/)
  assert.match(page, /rel="icon"/)
  assert.match(page, /mobile-nav-menu/)
  assert.match(css, /\.article-body h4/)
	assert.match(css, /\.article-layout/)
	assert.match(css, /\.mobile-nav \{[^}]*display: none/)
	assert.match(css, /@media \(max-width: 1024px\)[\s\S]*?\.mobile-nav \{ display: block; \}/)
  assert.match(css, /prefers-reduced-motion/)
})

test('template management binds real renderers and exposes isolated previews', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const page = readFileSync(new URL('../public.html', import.meta.url), 'utf8')
  const atlasPage = readFileSync(new URL('../public-atlas.html', import.meta.url), 'utf8')
  const atlasCSS = readFileSync(new URL('../assets/css/public-atlas.css', import.meta.url), 'utf8')
  assert.match(app, /item\.renderable/)
  assert.match(app, /data-template-details/)
  assert.match(app, /admin\/template-preview/)
  assert.match(app, /前台已切换/)
  assert.match(page, /theme-\{\{\.ThemeKey\}\}/)
  assert.match(page, /public-atlas\.css/)
  assert.match(atlasPage, /define "public-atlas\.html"/)
  assert.match(atlasCSS, /\.theme-atlas-commerce/)
  assert.match(atlasCSS, /@media \(max-width: 780px\)/)
  assert.match(atlasCSS, /prefers-reduced-motion/)
})

test('template rows expand into a real safe multi-file editor', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  const server = readFileSync(new URL('../../internal/httpserver/server.go', import.meta.url), 'utf8')
  const defaults = readFileSync(new URL('../../internal/database/theme_files.go', import.meta.url), 'utf8')
  for (const label of ['头部', '尾部', '首页', '栏目页', '产品栏目页', '内容页', '产品详情页', '单页面']) assert.match(defaults, new RegExp(label))
  assert.match(app, /data-template-toggle/)
  assert.match(app, /aria-controls="template-workspace-/)
  assert.match(app, /data-template-source/)
  assert.match(app, /data-template-validate/)
  assert.match(app, /data-template-save/)
  assert.match(app, /\/api\/v1\/templates\/\$\{encodeURIComponent\(id\)\}\/files/)
  assert.match(app, /当前输入已保留/)
  assert.match(app, /安全草稿/)
  assert.match(css, /\.template-editor-layout/)
  assert.match(css, /\.template-file-tree/)
  assert.match(css, /\.template-source/)
  assert.match(css, /@media \(max-width: 720px\)[\s\S]*?\.template-editor-layout \{ display: block; \}/)
  assert.match(css, /prefers-reduced-motion/)
  assert.match(server, /\/templates\/\{themeID\}\/files\/\{fileKey\}\/validate/)
})

test('product template files expose separate detail and category contracts', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const defaults = readFileSync(new URL('../../internal/database/theme_files.go', import.meta.url), 'utf8')
  const editor = readFileSync(new URL('../../internal/filestore/theme_editor.go', import.meta.url), 'utf8')
  assert.match(defaults, /Key: "product_detail"/)
  assert.match(defaults, /Key: "product_category"/)
  assert.match(defaults, /\.Content\.Gallery/)
  assert.match(defaults, /\.TaxonomyName/)
  assert.match(editor, /"product_detail": true/)
  assert.match(editor, /"product_category": true/)
  assert.match(app, /产品详情数据/)
  assert.match(app, /产品栏目数据/)
  assert.match(app, /打开产品管理测试/)
  assert.match(app, /管理产品栏目/)
})

test('single pages have their own management route, create flow and explicit index policy', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  const handlers = readFileSync(new URL('../../internal/httpserver/catalog_handlers.go', import.meta.url), 'utf8')
  const catalog = readFileSync(new URL('../../internal/catalog/catalog.go', import.meta.url), 'utf8')
  assert.match(html, /data-content-subnav/)
  assert.match(html, /section=pages/)
  assert.match(app, /function contentSection\(\)/)
  assert.match(app, /function contentModuleConfig\(\)/)
  assert.match(app, /content_type=page/)
  assert.match(app, /data-page-preset/)
  assert.match(app, /data-page-layout="\$\{preset\.layout\}"/)
  assert.match(app, /data-page-template="\$\{preset\.template\}"/)
  assert.match(app, /选择单页面模板/)
  assert.match(app, /page\/contact/)
  assert.match(app, /关于我们/)
  assert.match(app, /联系我们/)
  assert.match(app, /preset\.dataset\.pageLayout/)
  assert.match(app, /专题页面/)
  assert.match(app, /data-template-file="\$\{escapeHtml\(file\.key\)\}"/)
  assert.match(app, /template-page-manager-link/)
  assert.match(app, /template-page-create-link/)
  assert.match(app, /新建单页面默认 noindex/)
  assert.match(app, /payload\.content_type === 'page' \? \(payload\.index_policy === 'index'/)
  assert.match(app, /单页面“\$\{payload\.title\}”已创建，已显示在单页面列表/)
  assert.match(css, /\.page-preset-panel/)
  assert.match(css, /\.page-noindex-note/)
  assert.match(handlers, /ContentType:\s*r\.URL\.Query\(\)\.Get\("content_type"\)/)
  assert.match(catalog, /func \(s \*Service\) ContentCountsForType/)
})

test('contact page templates auto-bind a scoped enquiry form while keeping advanced editing available', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  const publicTemplate = readFileSync(new URL('../public.html', import.meta.url), 'utf8')
  const server = readFileSync(new URL('../../internal/httpserver/server.go', import.meta.url), 'utf8')
  const forms = readFileSync(new URL('../../internal/catalog/forms.go', import.meta.url), 'utf8')
  const catalog = readFileSync(new URL('../../internal/catalog/catalog.go', import.meta.url), 'utf8')
  assert.match(app, /contactPageFormManagerMarkup/)
  assert.doesNotMatch(app, /contactFormOnboardingMarkup/)
  assert.doesNotMatch(app, /save-and-build/)
  assert.doesNotMatch(app, /openContactBuilderAfterSave/)
  assert.match(app, /自动生成并绑定标准安全询盘表单/)
  assert.match(app, /保存页面并自动生成/)
  assert.match(app, /data-contact-action="edit"/)
  assert.match(forms, /func ensureDefaultContactFormTx/)
  assert.match(forms, /contact-enquiry-%d/)
  assert.match(catalog, /ensureDefaultContactFormTx/)
  assert.match(app, /data-contact-action="submissions"/)
  assert.match(app, /data-form-submission-status/)
  assert.match(app, /data-contact-builder/)
  assert.match(app, /data-builder-add/)
  assert.match(app, /data-builder-item/)
  assert.match(app, /data-builder-prop/)
  assert.match(app, /data-builder-submit/)
  assert.match(app, /submit_label/)
  assert.match(app, /function addContactBuilderItem/)
  assert.match(app, /data-builder-move-up/)
  assert.match(app, /data-builder-move-down/)
  assert.match(app, /data-builder-remove/)
  assert.match(app, /addEventListener\('dragstart'/)
  assert.match(app, /addEventListener\('dragover'/)
  assert.match(app, /addEventListener\('drop'/)
  assert.match(app, /\/api\/v1\/content-locales\/\$\{encodeURIComponent\(pageID\)\}\/form/)
  assert.match(css, /\.contact-form-manager/)
  assert.match(css, /\.contact-form-builder/)
  assert.match(css, /\.contact-builder-palette/)
  assert.match(css, /\.contact-builder-canvas/)
  assert.match(css, /\.contact-builder-submit/)
  assert.match(css, /\.form-submission-table/)
  assert.match(publicTemplate, /action="\{\{\.Form\.Action\}\}"/)
  assert.match(server, /\/content-locales\/\{contentLocaleID\}\/form/)
})

test('taxonomy is nested under content management in the primary navigation', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(html, /data-content-subnav[\s\S]*data-content-section="taxonomy"[^>]*>栏目与标签<\/a>/)
  assert.doesNotMatch(html, /<a[^>]+data-route="taxonomy"[^>]*>[\s\S]*栏目与标签<\/a>/)
  assert.match(app, /route === 'taxonomy' && link\.dataset\.route === 'content'/)
  assert.match(app, /route === 'taxonomy' && link\.dataset\.contentSection === 'taxonomy'/)
})

test('product information exposes product list and category management as nested navigation', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(html, /data-route="products"[^>]*>[\s\S]*产品信息<\/span>/)
  assert.match(html, /data-product-subnav[\s\S]*data-product-section="products"[^>]*>产品管理<\/a>/)
  assert.match(html, /data-product-subnav[\s\S]*data-product-section="categories"[^>]*>产品栏目<\/a>/)
  assert.doesNotMatch(html, /<a[^>]+data-route="product-categories"[^>]*>[\s\S]*产品栏目<\/a>/)
  assert.match(app, /route === 'products' && link\.dataset\.productSection === 'products'/)
  assert.match(app, /route === 'product-categories' && link\.dataset\.route === 'products'/)
  assert.match(app, /route === 'product-categories' && link\.dataset\.productSection === 'categories'/)
})

test('site editor exposes per-language template choices and live frontend preview', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /data-site-editor-tab/)
  assert.match(app, /data-site-template-choice/)
  assert.match(app, /data-site-template-frame/)
  assert.match(app, /siteTemplatePreviewPath/)
  assert.match(app, /data-site-language-select/)
  assert.match(app, /function selectSiteTemplateLanguage/)
  assert.match(app, /data-site-editor-tab="languages"/)
  assert.match(app, /function siteLanguageOverview/)
  assert.match(app, /data-site-language-tab/)
  assert.match(app, /每种语言独立绑定模板与前台站点/)
  assert.match(app, /data-site-editor-tab="seo"/)
  assert.match(app, /name="seo_title"/)
  assert.match(app, /name="seo_description"/)
  assert.match(app, /payload\.seo_description/)
  assert.match(app, /name="favicon_media_id"/)
  assert.match(app, /data-site-favicon-upload/)
  assert.match(app, /uploadSiteFavicon/)
  assert.match(app, /保存绑定后前台正式切换/)
  assert.match(app, /模板绑定已保存，前台已切换/)
  assert.match(css, /\.site-editor-shell/)
  assert.match(css, /\.site-template-language-picker/)
  assert.match(css, /\.site-favicon-selector/)
  assert.match(css, /\.site-template-option/)
  assert.match(css, /\.site-template-preview-frame/)
  assert.match(css, /\.site-language-card/)
  assert.match(css, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(css, /@media \(max-width: 720px\)[\s\S]*?\.site-template-layout \{ grid-template-columns: 1fr; \}/)
})

test('new site creation chooses a safe initial template and sends its binding', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /function siteCreateTemplateFields/)
  assert.match(app, /data-site-create-template-choice/)
  assert.match(app, /name="default_theme_package_id"/)
  assert.match(app, /render_key === 'global-route'/)
  assert.match(app, /default_theme_package_id: Number\(formValue\(entityForm, 'default_theme_package_id'\) \|\| 0\)/)
  assert.match(app, /route === 'sites' && can\('templates\.manage'\) \? await loadTemplates\(\) : \[\]/)
  assert.match(app, /function updateSiteCreateTemplateSelection/)
  assert.match(css, /\.site-create-template-section/)
  assert.match(css, /\.site-create-template-card\.is-selected/)
  assert.match(css, /@media \(max-width: 720px\)[\s\S]*?\.site-create-template-grid \{ grid-template-columns: 1fr; \}/)
})

test('media, users, audit and system modules use real APIs instead of demo rows', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const data = readFileSync(new URL('../assets/js/data.mjs', import.meta.url), 'utf8')
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  assert.match(app, /fetchJSON\('\/api\/v1\/media\?limit=100'\)/)
  assert.match(app, /fetchJSON\('\/api\/v1\/security\/users'\)/)
  assert.match(app, /fetchJSON\('\/api\/v1\/audit\?limit=100'\)/)
  assert.match(app, /fetchJSON\('\/api\/v1\/system\/status'\)/)
  assert.match(app, /\/api\/v1\/system\/backups/)
  assert.match(app, /data-media-edit/)
  assert.match(app, /data-media-delete/)
  assert.match(app, /data-user-edit/)
  assert.match(app, /data-audit-view/)
  assert.match(html, /data-route="audit"/)
  assert.match(data, /jobs:\s*\{[\s\S]*?rows: \[\]/)
	for (const route of ['sites', 'languages', 'content', 'taxonomy', 'templates', 'urls', 'publishing']) {
		assert.match(data, new RegExp(`${route}:\\s*\\{[\\s\\S]*?rows: \\[\\]`), `${route} must not retain demo rows`)
	}
  assert.doesNotMatch(html, /缓存命中率[^<]*<\/span><strong>96%/)
	assert.doesNotMatch(html, /2 个发布任务失败|18 条本土化内容待审核|SEO 检查已完成/)
	assert.match(html, /id="notification-items"/)
	assert.match(app, /来自真实内容状态/)
	assert.match(app, /formatDate\(item\.last_login_at\)/)
})

test('AI settings centralizes multiple providers and model presets without feature assignment UI', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  assert.match(html, /data-settings-section="ai"/)
  assert.match(html, /id="ai-provider-dialog"/)
  assert.match(app, /fetchJSON\('\/api\/v1\/system\/ai'\)/)
  assert.match(app, /\/api\/v1\/system\/ai\/providers/)
  assert.match(app, /aiProviderPresets/)
  assert.match(app, /ai-model-presets/)
  assert.match(app, /API Key 使用主密钥派生的 AES-GCM 密钥加密保存/)
  assert.match(app, /AI 结果是否需要审核由具体功能流程决定/)
  assert.match(app, /AI 接口与模型/)
  assert.match(app, /deepseek-v4-flash/)
  assert.match(app, /deepseek-v4-pro/)
  assert.match(app, /ai-status-detail/)
  assert.match(app, /provider\?\.timeout_seconds \|\| 120/)
  assert.match(app, /长篇本土化建议使用 120 秒/)
  assert.doesNotMatch(app, /用途分配/)
  assert.doesNotMatch(app, /本月调用量|本月成本估算|18,426|326\.80/)
  assert.match(css, /\.ai-provider-table/)
  assert.doesNotMatch(css, /\.ai-route-form/)
})

test('SEO centre shows one live sitemap and robots entry per accessible site', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  assert.match(app, /fetchJSON\('\/api\/v1\/seo\/sitemaps'\)/)
  assert.match(app, /function renderSEOCenter/)
  assert.match(app, /function seoSection\(\)/)
  assert.match(app, /function renderSEOTabs\(/)
  assert.match(app, /link\.dataset\.seoSection/)
  assert.match(app, /每个站点一份动态 sitemap\.xml/)
  assert.match(app, /系统自动生成 · 只读/)
  assert.match(app, /系统只读/)
  assert.match(app, /单页面 noindex/)
  assert.match(app, /robots 自动化策略/)
  assert.match(app, /每个站点一份动态 robots\.txt/)
  assert.match(app, /每个站点一行，查看规则状态后直接进入对应站点编辑/)
  assert.match(app, /发布状态/)
  assert.match(app, /正式 robots/)
  assert.match(app, /data-seo-robots-edit[\s\S]*?<span>编辑<\/span>/)
  assert.match(app, /data-seo-robots-create/)
  assert.match(app, /data-seo-robots-help/)
  assert.match(app, /openSiteRobotsDialog/)
  assert.match(app, /\/api\/v1\/seo\/robots\//)
  assert.match(app, /function seoSiteID\(site\)/)
  assert.match(app, /site\?\.site_id \?\? site\?\.id/)
  assert.match(app, /data-site-id="\$\{escapeHtml\(siteID\)\}"/)
  assert.match(app, /liveState\.seoSitemaps\?\.sites\?\.find/)
  assert.match(app, /当前 robots 列表已过期，请刷新状态后再编辑/)
  assert.match(app, /后台服务未连接，请确认 127\.0\.0\.1:8080 已启动后再重试/)
  assert.doesNotMatch(app, /data-seo-sitemap-edit/)
  assert.match(app, /data-seo-refresh/)
  assert.match(app, /site\.sitemap_url/)
  assert.match(app, /site\.robots_url/)
  assert.match(css, /\.seo-sitemap-table/)
  assert.match(css, /\.seo-subnav/)
  assert.match(css, /\.seo-tabs/)
  assert.match(css, /\.seo-robots-table/)
  assert.match(css, /\.seo-robots-entry/)
  assert.match(css, /\.seo-robots-status/)
  assert.match(css, /\.seo-machine-url/)
  assert.match(css, /\.seo-operation-note/)
  assert.match(html, /data-seo-section="sitemap"/)
  assert.match(html, /data-seo-section="robots"/)
})

test('spider statistics is a real, filterable SEO report with safe export', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  assert.match(html, /data-seo-section="spider"/)
  assert.match(app, /fetchJSON\(`\/api\/v1\/seo\/spider\?site_id=/)
  assert.match(app, /function renderSpiderStats\(\)/)
  assert.match(app, /data-spider-site/)
  assert.match(app, /data-spider-bot/)
  assert.match(app, /data-spider-status/)
  assert.match(app, /data-spider-custom-range/)
  assert.match(app, /data-spider-export/)
  assert.match(app, /function exportSpiderCSV\(\)/)
  assert.match(app, /\^\[=\+\\-@\]/)
  assert.match(app, /不保存 IP、完整 User-Agent、Cookie 或查询参数/)
  assert.match(css, /\.spider-controls/)
  assert.match(css, /\.spider-grid/)
  assert.match(css, /\.spider-chart/)
  assert.match(css, /\.spider-table/)
  assert.match(css, /\.spider-privacy-note/)
})

test('spider statistics groups the most crawled pages by search and AI crawler family', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /function spiderTopPagesPanel\(items = \[\]\)/)
  assert.match(app, /top_pages/)
  assert.match(app, /本周期抓取最多的页面/)
  assert.match(app, /Google/)
  assert.match(app, /Bing/)
  assert.match(app, /GPT \/ OpenAI/)
  assert.match(app, /Gemini/)
  assert.match(app, /data-spider-engine/)
  assert.match(app, /未表示已验证的蜘蛛身份/)
  assert.match(css, /\.spider-engine-tabs/)
  assert.match(css, /\.spider-top-pages-table/)
})

test('backup centre exposes complete encrypted backup export and verified import', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /function renderBackupSettings/)
  assert.match(app, /数据库 \+ 媒体 \+ 模板/)
  assert.match(app, /data-backup-create/)
  assert.match(app, /data-backup-import/)
  assert.match(app, /system\/backups\/import/)
  assert.match(app, /\/download/)
  assert.match(app, /backup-restore/)
  assert.match(app, /data-backup-delete/)
  assert.match(app, /data-backup-bulk-delete/)
  assert.match(app, /backup_ids/)
  assert.match(css, /\.backup-records-table/)
  assert.match(css, /\.backup-selection-bar/)
  assert.match(css, /\.backup-restore-guide/)
})

test('taxonomy tag URLs use readable names with an automatic conflict fallback', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const taxonomy = readFileSync(new URL('../../internal/catalog/taxonomy.go', import.meta.url), 'utf8')
  assert.match(app, /空格转为下划线/)
  assert.match(taxonomy, /func taxonomyTagNameSlug\(/)
  assert.match(taxonomy, /kind == "tag"/)
  assert.match(taxonomy, /generatedTaxonomyFallbackSlug/)
  assert.match(taxonomy, /occupied/)
})
