import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { contentEditorSlug, contentWordCount, escapeHtml, filterRows, normalizeTags, routeFromHash, sitePublicPath, statusClass } from '../assets/js/utils.mjs'

test('routeFromHash parses admin routes safely', () => {
  assert.equal(routeFromHash('#/admin'), 'dashboard')
  assert.equal(routeFromHash('#/admin/languages?enabled=1'), 'languages')
  assert.equal(routeFromHash('#/unknown'), 'dashboard')
})

test('statusClass maps semantic statuses', () => {
  assert.equal(statusClass('发布失败'), 'badge-red')
  assert.equal(statusClass('待审核'), 'badge-amber')
  assert.equal(statusClass('已发布'), 'badge-green')
})

test('filterRows searches all visible fields and filters status', () => {
  const rows = [{ id: 1, name: '德国站', status: '运行中' }, { id: 2, name: '法国站', status: '维护中' }]
  assert.equal(filterRows(rows, '德国', '全部站点').length, 1)
  assert.equal(filterRows(rows, '', '维护中').length, 1)
})

test('escapeHtml prevents executable markup injection', () => {
  assert.equal(escapeHtml('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;')
})

test('normalizeTags accepts Chinese commas, removes duplicates and enforces limit', () => {
  assert.deepEqual(normalizeTags('物流, 欧洲专线，物流\n门到门'), ['物流', '欧洲专线', '门到门'])
  assert.deepEqual(normalizeTags('A,a,B', 2), ['A', 'B'])
})

test('dialog close and cancel actions bypass required-field validation', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  assert.match(html, /formnovalidate value="cancel" aria-label="关闭"/)
  assert.match(html, /formnovalidate value="cancel">取消<\/button>/)
})

test('content editor creates safe deterministic slugs', () => {
  assert.equal(contentEditorSlug('  Global_Logistics / SEO Guide  '), 'global-logistics/seo-guide')
  assert.equal(contentEditorSlug('中文标题', new Date('2026-08-27T00:00:00Z')), 'article-20260827')
})

test('content editor counts CJK characters and latin words', () => {
  assert.equal(contentWordCount('多语言 SEO helps global logistics'), 7)
  assert.equal(contentWordCount('  '), 0)
})

test('independent language sites use clean root paths', () => {
  assert.equal(sitePublicPath({ language_count: 1 }, 'it-IT', 'guide/spedizioni-internazionali'), '/guide/spedizioni-internazionali')
  assert.equal(sitePublicPath({ language_count: 1 }, 'de-DE'), '/')
  assert.equal(sitePublicPath({ language_count: 2 }, 'de-DE', 'ratgeber/logistik'), '/de-DE/ratgeber/logistik')
})

test('content editor route keeps its essential authoring and publishing controls', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(html, /id="content-editor-view"/)
  assert.match(app, /id="content-editor-form"/)
  assert.match(app, /data-rich-editor/)
  assert.match(app, /data-content-action="save"/)
  assert.match(app, /data-content-action="review"/)
  assert.match(app, /data-content-action="publish"/)
  assert.match(app, /Google SEO 设置/)
  assert.match(app, /name="cover_media_id"/)
  assert.match(app, /data-media-target.*content-cover|openMediaUploadDialog\('content-cover'\)/)
  assert.match(app, /cover_media_id:/)
})

test('content editor uploads and localizes pasted images instead of prompting for remote URLs', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(app, /data-rich-image-input/)
  assert.match(app, /contentEditorView\.addEventListener\('paste'/)
  assert.match(app, /clipboard\.items/)
  assert.match(app, /\/api\/v1\/media\/upload/)
  assert.match(app, /\/api\/v1\/media\/import/)
  assert.match(app, /正在本地化/)
  assert.doesNotMatch(app, /输入图片地址；正式使用时建议从媒体中心选择/)
})

test('content editor includes heading four and SEO AI fallback controls', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(app, /<option value="h4">标题 4<\/option>/)
  assert.match(app, /data-content-action="seo-extract"/)
  assert.match(app, /\/api\/v1\/content\/seo-suggestions/)
  assert.match(app, /applyLocalSEODefaults/)
})

test('taxonomy is real data and content editor reuses scoped category and tag suggestions', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const data = readFileSync(new URL('../assets/js/data.mjs', import.meta.url), 'utf8')
  assert.match(app, /fetchJSON\(siteScopedAPIPath\('\/api\/v1\/taxonomy\/terms'\)\)/)
  assert.match(app, /content-category-suggestions/)
  assert.match(app, /content-tag-suggestions/)
  assert.match(app, /refreshContentTaxonomySuggestions/)
  assert.match(app, /保存时自动创建/)
  assert.match(data, /taxonomy:\s*\{[\s\S]*?rows: \[\]/)
})

test('top site switcher scopes operational modules and refreshes their cached data', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /const siteScopedRoutes = new Set\(\['content', 'taxonomy', 'urls', 'publishing', 'localization'\]\)/)
  assert.match(app, /siteScopedAPIPath\(contentPath\)/)
  assert.match(app, /content_type=page/)
  assert.match(app, /siteScopedAPIPath\('\/api\/v1\/taxonomy\/terms'\)/)
  assert.match(app, /siteScopedAPIPath\('\/api\/v1\/urls\/redirects'\)/)
  assert.match(app, /siteScopedAPIPath\('\/api\/v1\/publishing\/releases'\)/)
  assert.match(app, /siteScopedAPIPath\('\/api\/v1\/localization\/jobs'\)/)
  assert.match(app, /for \(const route of siteScopedRoutes\)/)
  assert.match(app, /moduleState\.selected\.clear\(\)/)
  assert.match(app, /await loadRoute\('sites'\)/)
  assert.match(app, /role="menuitemradio" aria-checked="false"/)
  assert.match(app, /当前站点：/)
  assert.match(css, /\.site-menu button\[aria-checked="true"\]/)
})

test('AI localization uses published English as source and only creates review drafts for active template-bound sites', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const data = readFileSync(new URL('../assets/js/data.mjs', import.meta.url), 'utf8')
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  assert.match(html, /id="localization-dialog"/)
  assert.match(app, /defaultEnglishSite/)
  assert.match(app, /item\.status !== 'published'/)
  assert.match(app, /\/localization-options/)
  assert.match(app, /\/localize`/)
  assert.match(app, /scope: 'full', overwrite: false/)
  assert.match(app, /不会自动发布/)
  assert.match(app, /target\.existing/)
  assert.match(app, /target\.template_bound/)
  assert.match(app, /target\.site_online/)
  assert.match(app, /target\.template_online/)
  assert.match(app, /同步到已上线分站/)
  assert.match(app, /locked_terms/)
  assert.match(app, /forbidden_terms/)
  assert.match(data, /以英语为源内容/)
})

test('content revisions support field comparison and safe restore as a new draft', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /data-content-action="revisions"/)
  assert.match(app, /function revisionDiffMarkup/)
  assert.match(app, /data-revision-restore/)
  assert.match(app, /\/revisions\/\$\{encodeURIComponent\(revisionID\)\}\/restore/)
  assert.match(app, /新的草稿版本/)
  assert.match(css, /\.revision-diff-list/)
})

test('global search hides quick actions outside the current RBAC permissions', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const data = readFileSync(new URL('../assets/js/data.mjs', import.meta.url), 'utf8')
  assert.match(app, /quickActions\.filter\(\(item\) => can\(item\.permission\)/)
  assert.match(data, /permission: 'content\.write'/)
  assert.match(data, /permission: 'jobs\.manage'/)
})

test('site and content lists expose explicit row actions and bulk deletion controls', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /data-site-edit/)
  assert.match(app, /data-site-delete/)
  assert.match(app, /data-bulk-delete-sites/)
  assert.match(app, /data-content-edit/)
  assert.match(app, /data-content-view/)
	assert.match(app, /\/admin\/content-preview\//)
	assert.match(app, /在新窗口使用前端模板安全预览/)
  assert.match(app, /data-content-delete/)
  assert.match(app, /data-bulk-delete-contents/)
  assert.match(app, /data-bulk-update-status/)
  assert.match(app, /data-bulk-update-category/)
  assert.match(app, /\/api\/v1\/contents\/bulk-update/)
  assert.match(app, /任一版本冲突时整批回滚/)
  assert.match(app, /删除内容组会同时移除其全部站点 \/ 语言版本/)
  assert.match(app, /content-readonly-frame/)
  assert.match(app, /sitePreviewURL/)
  assert.match(app, /row-action-edit/)
  assert.match(app, /row-action-preview/)
  assert.match(app, /i-edit|icon\('edit'/)
  assert.match(app, /i-eye|icon\('eye'/)
  assert.match(app, /i-trash|icon\('trash'/)
  assert.match(app, /安全停用站点并保留内容与审计数据/)
  assert.match(css, /\.row-actions/)
  assert.match(css, /font-family: inherit/)
  assert.match(css, /\.row-action-button \.icon/)
  assert.match(css, /\.bulk-action-bar/)
})

test('published content links to the native multilingual frontend', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(app, /function contentFrontendPreviewURL/)
  assert.match(app, /function isScheduledContent/)
  assert.match(app, /打开前台页面/)
  assert.match(app, /item\.status === 'published'/)
  assert.match(app, /最多受 60 秒页面缓存影响/)
})

test('public template renders six-language SEO pages and CMS content', () => {
  const page = readFileSync(new URL('../public.html', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/public.css', import.meta.url), 'utf8')
  assert.match(page, /hreflang/)
  assert.match(page, /application\/ld\+json/)
  assert.match(page, /\.Content\.Body/)
  assert.match(page, /\.Published/)
	assert.match(page, /article-masthead/)
	assert.match(page, /\.Content\.ReadingMinutes/)
	assert.match(page, /\.Related/)
  assert.match(page, /language-picker/)
  assert.match(page, /rel="icon"/)
  assert.match(page, /mobile-nav-menu/)
  assert.match(css, /\.article-body h4/)
	assert.match(css, /\.article-layout/)
	assert.match(css, /\.mobile-nav \{[^}]*display: none/)
	assert.match(css, /@media \(max-width: 1024px\)[\s\S]*?\.mobile-nav \{ display: block; \}/)
  assert.match(css, /prefers-reduced-motion/)
})

test('template management binds real renderers and exposes isolated previews', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const page = readFileSync(new URL('../public.html', import.meta.url), 'utf8')
  const atlasPage = readFileSync(new URL('../public-atlas.html', import.meta.url), 'utf8')
  const atlasCSS = readFileSync(new URL('../assets/css/public-atlas.css', import.meta.url), 'utf8')
  assert.match(app, /item\.renderable/)
  assert.match(app, /data-template-details/)
  assert.match(app, /admin\/template-preview/)
  assert.match(app, /前台已切换/)
  assert.match(page, /theme-\{\{\.ThemeKey\}\}/)
  assert.match(page, /public-atlas\.css/)
  assert.match(atlasPage, /define "public-atlas\.html"/)
  assert.match(atlasCSS, /\.theme-atlas-commerce/)
  assert.match(atlasCSS, /@media \(max-width: 780px\)/)
  assert.match(atlasCSS, /prefers-reduced-motion/)
})

test('template rows expand into a real safe multi-file editor', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  const server = readFileSync(new URL('../../internal/httpserver/server.go', import.meta.url), 'utf8')
  const defaults = readFileSync(new URL('../../internal/database/theme_files.go', import.meta.url), 'utf8')
  for (const label of ['头部', '尾部', '首页', '栏目页', '内容页', '单页面']) assert.match(defaults, new RegExp(label))
  assert.match(app, /data-template-toggle/)
  assert.match(app, /aria-controls="template-workspace-/)
  assert.match(app, /data-template-source/)
  assert.match(app, /data-template-validate/)
  assert.match(app, /data-template-save/)
  assert.match(app, /\/api\/v1\/templates\/\$\{encodeURIComponent\(id\)\}\/files/)
  assert.match(app, /当前输入已保留/)
  assert.match(app, /安全草稿/)
  assert.match(css, /\.template-editor-layout/)
  assert.match(css, /\.template-file-tree/)
  assert.match(css, /\.template-source/)
  assert.match(css, /@media \(max-width: 720px\)[\s\S]*?\.template-editor-layout \{ display: block; \}/)
  assert.match(css, /prefers-reduced-motion/)
  assert.match(server, /\/templates\/\{themeID\}\/files\/\{fileKey\}\/validate/)
})

test('single pages have their own management route, create flow and fixed noindex policy', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  const handlers = readFileSync(new URL('../../internal/httpserver/catalog_handlers.go', import.meta.url), 'utf8')
  const catalog = readFileSync(new URL('../../internal/catalog/catalog.go', import.meta.url), 'utf8')
  assert.match(html, /data-content-subnav/)
  assert.match(html, /section=pages/)
  assert.match(app, /function contentSection\(\)/)
  assert.match(app, /function contentModuleConfig\(\)/)
  assert.match(app, /content_type=page/)
  assert.match(app, /data-page-preset/)
  assert.match(app, /关于我们/)
  assert.match(app, /联系我们/)
  assert.match(app, /专题页面/)
  assert.match(app, /data-template-file="\$\{escapeHtml\(file\.key\)\}"/)
  assert.match(app, /template-page-manager-link/)
  assert.match(app, /template-page-create-link/)
  assert.match(app, /单页面固定不收录/)
  assert.match(app, /payload\.content_type === 'page' \? false/)
  assert.match(css, /\.page-preset-panel/)
  assert.match(css, /\.page-noindex-note/)
  assert.match(handlers, /ContentType:\s*r\.URL\.Query\(\)\.Get\("content_type"\)/)
  assert.match(catalog, /func \(s \*Service\) ContentCountsForType/)
})

test('taxonomy is nested under content management in the primary navigation', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  assert.match(html, /data-content-subnav[\s\S]*data-content-section="taxonomy"[^>]*>栏目与标签<\/a>/)
  assert.doesNotMatch(html, /<a[^>]+data-route="taxonomy"[^>]*>[\s\S]*栏目与标签<\/a>/)
  assert.match(app, /route === 'taxonomy' && link\.dataset\.route === 'content'/)
  assert.match(app, /route === 'taxonomy' && link\.dataset\.contentSection === 'taxonomy'/)
})

test('site editor exposes per-language template choices and live frontend preview', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /data-site-editor-tab/)
  assert.match(app, /data-site-template-choice/)
  assert.match(app, /data-site-template-frame/)
  assert.match(app, /siteTemplatePreviewPath/)
  assert.match(app, /data-site-language-select/)
  assert.match(app, /function selectSiteTemplateLanguage/)
  assert.match(app, /data-site-editor-tab="languages"/)
  assert.match(app, /function siteLanguageOverview/)
  assert.match(app, /data-site-language-tab/)
  assert.match(app, /每种语言独立绑定模板与前台站点/)
  assert.match(app, /data-site-editor-tab="seo"/)
  assert.match(app, /name="seo_title"/)
  assert.match(app, /name="seo_description"/)
  assert.match(app, /payload\.seo_description/)
  assert.match(app, /name="favicon_media_id"/)
  assert.match(app, /data-site-favicon-upload/)
  assert.match(app, /uploadSiteFavicon/)
  assert.match(app, /保存绑定后前台正式切换/)
  assert.match(app, /模板绑定已保存，前台已切换/)
  assert.match(css, /\.site-editor-shell/)
  assert.match(css, /\.site-template-language-picker/)
  assert.match(css, /\.site-favicon-selector/)
  assert.match(css, /\.site-template-option/)
  assert.match(css, /\.site-template-preview-frame/)
  assert.match(css, /\.site-language-card/)
  assert.match(css, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(css, /@media \(max-width: 720px\)[\s\S]*?\.site-template-layout \{ grid-template-columns: 1fr; \}/)
})

test('new site creation chooses a safe initial template and sends its binding', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  assert.match(app, /function siteCreateTemplateFields/)
  assert.match(app, /data-site-create-template-choice/)
  assert.match(app, /name="default_theme_package_id"/)
  assert.match(app, /render_key === 'global-route'/)
  assert.match(app, /default_theme_package_id: Number\(formValue\(entityForm, 'default_theme_package_id'\) \|\| 0\)/)
  assert.match(app, /route === 'sites' && can\('templates\.manage'\) \? await loadTemplates\(\) : \[\]/)
  assert.match(app, /function updateSiteCreateTemplateSelection/)
  assert.match(css, /\.site-create-template-section/)
  assert.match(css, /\.site-create-template-card\.is-selected/)
  assert.match(css, /@media \(max-width: 720px\)[\s\S]*?\.site-create-template-grid \{ grid-template-columns: 1fr; \}/)
})

test('media, users, audit and system modules use real APIs instead of demo rows', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const data = readFileSync(new URL('../assets/js/data.mjs', import.meta.url), 'utf8')
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  assert.match(app, /fetchJSON\('\/api\/v1\/media\?limit=100'\)/)
  assert.match(app, /fetchJSON\('\/api\/v1\/security\/users'\)/)
  assert.match(app, /fetchJSON\('\/api\/v1\/audit\?limit=100'\)/)
  assert.match(app, /fetchJSON\('\/api\/v1\/system\/status'\)/)
  assert.match(app, /\/api\/v1\/system\/backups/)
  assert.match(app, /data-media-edit/)
  assert.match(app, /data-media-delete/)
  assert.match(app, /data-user-edit/)
  assert.match(app, /data-audit-view/)
  assert.match(html, /data-route="audit"/)
  assert.match(data, /jobs:\s*\{[\s\S]*?rows: \[\]/)
	for (const route of ['sites', 'languages', 'content', 'taxonomy', 'templates', 'urls', 'publishing']) {
		assert.match(data, new RegExp(`${route}:\\s*\\{[\\s\\S]*?rows: \\[\\]`), `${route} must not retain demo rows`)
	}
  assert.doesNotMatch(html, /缓存命中率[^<]*<\/span><strong>96%/)
	assert.doesNotMatch(html, /2 个发布任务失败|18 条本土化内容待审核|SEO 检查已完成/)
	assert.match(html, /id="notification-items"/)
	assert.match(app, /来自真实内容状态/)
	assert.match(app, /formatDate\(item\.last_login_at\)/)
})

test('AI settings centralizes multiple providers and model presets without feature assignment UI', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  assert.match(html, /data-settings-section="ai"/)
  assert.match(html, /id="ai-provider-dialog"/)
  assert.match(app, /fetchJSON\('\/api\/v1\/system\/ai'\)/)
  assert.match(app, /\/api\/v1\/system\/ai\/providers/)
  assert.match(app, /aiProviderPresets/)
  assert.match(app, /ai-model-presets/)
  assert.match(app, /API Key 使用主密钥派生的 AES-GCM 密钥加密保存/)
  assert.match(app, /AI 结果是否需要审核由具体功能流程决定/)
  assert.match(app, /AI 接口与模型/)
  assert.doesNotMatch(app, /用途分配/)
  assert.doesNotMatch(app, /本月调用量|本月成本估算|18,426|326\.80/)
  assert.match(css, /\.ai-provider-table/)
  assert.doesNotMatch(css, /\.ai-route-form/)
})

test('SEO centre shows one live sitemap and robots entry per accessible site', () => {
  const app = readFileSync(new URL('../assets/js/app.mjs', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../assets/css/admin.css', import.meta.url), 'utf8')
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  assert.match(app, /fetchJSON\('\/api\/v1\/seo\/sitemaps'\)/)
  assert.match(app, /function renderSEOCenter/)
  assert.match(app, /function seoSection\(\)/)
  assert.match(app, /function renderSEOTabs\(/)
  assert.match(app, /link\.dataset\.seoSection/)
  assert.match(app, /每个站点一份动态 sitemap\.xml/)
  assert.match(app, /单页面自动 noindex/)
  assert.match(app, /robots 自动化策略/)
  assert.match(app, /每个站点一份动态 robots\.txt/)
  assert.match(app, /正式 robots/)
  assert.match(app, /data-seo-refresh/)
  assert.match(app, /site\.sitemap_url/)
  assert.match(app, /site\.robots_url/)
  assert.match(css, /\.seo-sitemap-table/)
  assert.match(css, /\.seo-subnav/)
  assert.match(css, /\.seo-tabs/)
  assert.match(css, /\.seo-robots-table/)
  assert.match(css, /\.seo-machine-url/)
  assert.match(css, /\.seo-operation-note/)
  assert.match(html, /data-seo-section="sitemap"/)
  assert.match(html, /data-seo-section="robots"/)
})
