package httpserver

import "strings"

// publicCopyFor supplies complete native-language navigation and landing-page
// copy for the six initial markets. A custom language added in the admin falls
// back to English until its template/copy package is installed.
func publicCopyFor(locale string) publicCopy {
	code := strings.ToLower(strings.Split(strings.TrimSpace(locale), "-")[0])
	copy, ok := publicCopies[code]
	if !ok {
		copy = publicCopies["en"]
		code = "en"
	}
	copy.Services = homeServices[code]
	copy.TrustItems = homeTrustItems[code]
	copy.AdvantagesTitle = homeAdvantages[code].Title
	copy.Advantages = homeAdvantages[code].Items
	copy.ProcessTitle = homeProcess[code].Title
	copy.ProcessBody = homeProcess[code].Body
	copy.ProcessSteps = homeProcess[code].Steps
	markers := []string{"01", "02", "03", "04"}
	if code == "it" {
		markers = []string{"I", "II", "III", "IV"}
	}
	for i := range copy.ProcessSteps {
		copy.ProcessSteps[i].Marker = markers[i]
	}
	copy.IndustriesTitle = homeIndustries[code].Title
	copy.IndustriesBody = homeIndustries[code].Body
	copy.Industries = homeIndustries[code].Items
	copy.FAQTitle = homeFAQs[code].Title
	copy.FAQs = homeFAQs[code].Items
	copy.PageHome, copy.PageServices, copy.PageIndustries, copy.PageSolutions = fixedPageLabels[code][0], fixedPageLabels[code][1], fixedPageLabels[code][2], fixedPageLabels[code][3]
	copy.PageWorkflow, copy.PageScope, copy.PageGuides, copy.PageContact = fixedPageLabels[code][4], fixedPageLabels[code][5], fixedPageLabels[code][6], fixedPageLabels[code][7]
	copy.PageDecision, copy.PageFits, copy.PageNeeds, copy.PageBenefits = fixedPageLabels[code][8], fixedPageLabels[code][9], fixedPageLabels[code][10], fixedPageLabels[code][11]
	copy.PageIncluded, copy.PageConfirm, copy.PageFAQTitle, copy.PageFAQLead = fixedPageLabels[code][12], fixedPageLabels[code][13], fixedPageLabels[code][14], fixedPageLabels[code][15]
	copy.PageRelatedBack, copy.PageBackTop, copy.PageRelatedTitle = fixedPageLabels[code][16], fixedPageLabels[code][17], fixedPageLabels[code][18]
	copy.FixedFooter = fixedFooter[code]
	return copy
}

var fixedFooter = map[string]string{
	"en": "FreightVanta connects sourcing, packaging, bulk orders, inventory preparation, white-label planning, and fulfillment through practical operating briefs and confirmed scopes.",
	"de": "FreightVanta verbindet Beschaffung, Verpackung, Bulk-Bestellungen, Bestandsvorbereitung, White-Label-Planung und Fulfillment über klare Arbeitsbriefe und bestätigte Umfänge.",
	"fr": "FreightVanta relie sourcing, emballage, achats en volume, inventaire, marque blanche et fulfillment dans des briefs pratiques et des périmètres confirmés.",
	"es": "FreightVanta conecta abastecimiento, embalaje, compras al por mayor, inventario, marca blanca y fulfillment mediante briefs prácticos y alcances confirmados.",
	"it": "FreightVanta collega sourcing, packaging, acquisti in volume, inventario, private label e fulfillment tramite brief operativi e perimetri confermati.",
	"nl": "FreightVanta verbindt sourcing, verpakking, bulkinkoop, voorraad, private label en fulfillment via praktische briefs en bevestigde scopes.",
}

// fixedPageLabels is shared by the five service topics and four industry
// solutions. Keeping the shell labels here means a localized page never
// falls back to an English breadcrumb or section marker.
var fixedPageLabels = map[string][]string{
	"en": {"Home", "Services", "Industries", "Solutions", "How it works", "Scope", "Guides", "Contact", "The decision", "When this service fits", "What you need", "Why it helps", "FreightVanta can help coordinate", "Requires confirmation before it is promised", "Scope questions, answered before the operational conversation starts.", "Visible answers establish practical boundaries before an enquiry becomes a proposed scope.", "Back to top", "Back to top", "Continue with the handoff you need next."},
	"de": {"Startseite", "Leistungen", "Branchen", "Lösungen", "Ablauf", "Umfang", "Wissen", "Kontakt", "Die Entscheidung", "Wann diese Leistung passt", "Was Sie benötigen", "Ihr Nutzen", "FreightVanta kann koordinieren", "Vor einer Zusage zu bestätigen", "Fragen zum Umfang vor dem operativen Gespräch", "Klare Antworten grenzen den möglichen Leistungsumfang vor der Anfrage ab.", "Nach oben", "Nach oben", "Mit der nächsten Übergabe fortfahren"},
	"fr": {"Accueil", "Services", "Secteurs", "Solutions", "Processus", "Périmètre", "Guides", "Contact", "La décision", "Quand ce service est adapté", "Ce qu’il vous faut", "Ce que cela apporte", "FreightVanta peut coordonner", "À confirmer avant toute promesse", "Les questions de périmètre, avant l’échange opérationnel", "Des réponses visibles définissent les limites pratiques avant la demande.", "Haut de page", "Haut de page", "Poursuivre avec la prochaine transition"},
	"es": {"Inicio", "Servicios", "Sectores", "Soluciones", "Cómo funciona", "Alcance", "Guías", "Contacto", "La decisión", "Cuándo encaja este servicio", "Qué necesitamos", "Qué aporta", "FreightVanta puede coordinar", "Debe confirmarse antes de prometerlo", "Preguntas de alcance antes de la conversación operativa", "Las respuestas visibles fijan los límites prácticos antes de una solicitud.", "Volver arriba", "Volver arriba", "Continuar con la siguiente transferencia"},
	"it": {"Home", "Servizi", "Settori", "Soluzioni", "Come funziona", "Perimetro", "Guide", "Contatti", "La decisione", "Quando è adatto", "Cosa serve", "Il valore", "FreightVanta può coordinare", "Da confermare prima di prometterlo", "Domande sul perimetro prima del confronto operativo", "Risposte chiare definiscono i limiti pratici prima della richiesta.", "Torna su", "Torna su", "Continua con il prossimo passaggio"},
	"nl": {"Home", "Diensten", "Sectoren", "Oplossingen", "Zo werkt het", "Scope", "Gidsen", "Contact", "De beslissing", "Wanneer deze dienst past", "Wat u nodig heeft", "De waarde", "FreightVanta kan coördineren", "Eerst bevestigen voordat het wordt beloofd", "Scopevragen vóór het operationele gesprek", "Heldere antwoorden maken de praktische grenzen zichtbaar vóór een aanvraag.", "Naar boven", "Naar boven", "Ga door met de volgende overdracht"},
}

var guideIndexCopies = map[string]publicGuideIndexCopy{
	"en": {Kicker: "FROM THE FREIGHTVANTA DESK", Title: "Shipping intelligence for better decisions.", Body: "Practical guides for international freight, imports, Incoterms, supplier coordination and the decisions that sit between “ordered” and “delivered.”", FeaturedLabel: "FEATURED BRIEF", FeaturedTitle: "Ocean or air freight: choosing the right route.", FeaturedBody: "How to compare readiness, cargo profile, target window, documentation and handoffs before you book a movement.", LatestLabel: "LATEST BRIEF · 8 MIN READ", ReadLatest: "Read the latest brief", BrowseTopics: "Browse topics", ExplainLabel: "WHAT WE EXPLAIN", MoreTitle: "More from the desk.", MoreBody: "Practical notes on the details that sit between “ordered” and “delivered”.", NewsletterKicker: "KEEP THE NEXT DECISION CLOSE", NewsletterTitle: "One useful brief, once a month.", NewsletterBody: "Receive practical notes on China sourcing, freight routes, import preparation and fulfillment handoffs. No noise, just the next decision.", Subscribe: "Subscribe", Topics: []string{"All insights", "Import planning", "Sourcing", "Freight modes", "Fulfillment", "Packaging"}, FallbackTitles: []string{"Preparing documents before cargo moves.", "Packaging and insert planning.", "How to prepare a product sourcing brief."}, FallbackBodies: []string{"A practical checklist for commercial invoices, packing details and the next customs handoff.", "Keep approved boxes, labels and inserts attached to the preparation rule.", "Turn a product link, target quantity and market into a supplier-ready starting point."}},
	"de": {Kicker: "AUS DEM FREIGHTVANTA-WISSEN", Title: "Logistikwissen für sichere Entscheidungen.", Body: "Praktische Leitfäden zu Importvorbereitung, Incoterms, Lieferantenbriefing, See- und Luftfracht sowie den Entscheidungen zwischen Bestellung und Zustellung.", FeaturedLabel: "AUSGEWÄHLTER LEITFADEN", FeaturedTitle: "See- oder Luftfracht: Welche Route passt?", FeaturedBody: "So vergleichen Sie Warenbereitschaft, Ladungsprofil, Zeitfenster, Dokumente und Übergaben vor der Buchung.", LatestLabel: "AKTUELL · 8 MIN LESEZEIT", ReadLatest: "Leitfaden lesen", BrowseTopics: "Themen ansehen", ExplainLabel: "WAS WIR ERKLÄREN", MoreTitle: "Weitere Beiträge aus dem Team.", MoreBody: "Klare Hinweise zu den Details zwischen Bestellung und Zustellung.", NewsletterKicker: "DIE NÄCHSTE ENTSCHEIDUNG IM BLICK", NewsletterTitle: "Ein nützlicher Leitfaden pro Monat.", NewsletterBody: "Praktische Hinweise zu Beschaffung in China, Routen, Importvorbereitung und Fulfillment – ohne unnötige Nachrichten.", Subscribe: "Abonnieren", Topics: []string{"Alle Beiträge", "Importplanung", "Beschaffung", "Transportarten", "Fulfillment", "Verpackung"}, FallbackTitles: []string{"Dokumente vor dem Versand vorbereiten.", "Verpackung und Beileger planen.", "Ein belastbares Lieferantenbriefing erstellen."}, FallbackBodies: []string{"Checkliste für Rechnungen, Packdaten und die nächste Zollübergabe.", "Freigegebene Kartons, Etiketten und Beileger in einer Regel halten.", "Link, Menge und Zielmarkt in eine klare Anfrage übersetzen."}},
	"fr": {Kicker: "LE CARNET FREIGHTVANTA", Title: "Des ressources pour décider avec justesse.", Body: "Des guides pratiques sur l’import, les Incoterms, le brief fournisseur, le maritime et l’aérien, et les décisions entre la commande et la livraison.", FeaturedLabel: "GUIDE À LA UNE", FeaturedTitle: "Maritime ou aérien : choisir le bon relais.", FeaturedBody: "Comparer disponibilité, profil de la marchandise, délai cible, documents et transitions avant de réserver.", LatestLabel: "À LA UNE · 8 MIN DE LECTURE", ReadLatest: "Lire le guide", BrowseTopics: "Parcourir les sujets", ExplainLabel: "CE QUE NOUS ÉCLAIRONS", MoreTitle: "Depuis le bureau FreightVanta.", MoreBody: "Des repères clairs sur les détails entre « commandé » et « livré ».", NewsletterKicker: "GARDER LA PROCHAINE DÉCISION PROCHE", NewsletterTitle: "Un guide utile, une fois par mois.", NewsletterBody: "Recevez des notes pratiques sur le sourcing en Chine, les routes, l’import et le fulfillment. Pas de bruit, seulement le prochain choix.", Subscribe: "S’abonner", Topics: []string{"Tous les guides", "Préparer un import", "Sourcing", "Modes de transport", "Fulfillment", "Emballage"}, FallbackTitles: []string{"Préparer les documents avant le départ.", "Prévoir emballage et inserts.", "Structurer un brief fournisseur."}, FallbackBodies: []string{"Les informations utiles pour le prochain relais douanier.", "Garder les éléments de marque attachés à la préparation.", "Transformer lien, quantité et marché en demande comparable."}},
	"es": {Kicker: "DEL EQUIPO FREIGHTVANTA", Title: "Información para tomar mejores decisiones.", Body: "Guías prácticas sobre importación, Incoterms, brief de proveedores, transporte marítimo y aéreo y las decisiones entre pedir y entregar.", FeaturedLabel: "GUÍA DESTACADA", FeaturedTitle: "¿Marítimo o aéreo? Elige la ruta adecuada.", FeaturedBody: "Compara disponibilidad, tipo de carga, fecha objetivo, documentación y relevos antes de reservar.", LatestLabel: "ÚLTIMA GUÍA · 8 MIN DE LECTURA", ReadLatest: "Leer la guía", BrowseTopics: "Ver temas", ExplainLabel: "LO QUE EXPLICAMOS", MoreTitle: "Más notas del equipo.", MoreBody: "Claves prácticas para los detalles entre “pedido” y “entregado”.", NewsletterKicker: "MANTÉN CERCA LA PRÓXIMA DECISIÓN", NewsletterTitle: "Una guía útil al mes.", NewsletterBody: "Recibe notas sobre compras en China, rutas, importación y fulfillment. Sin ruido, solo el siguiente paso.", Subscribe: "Suscribirme", Topics: []string{"Todos los recursos", "Planificar la importación", "Sourcing", "Modos de transporte", "Fulfillment", "Packaging"}, FallbackTitles: []string{"Prepara los documentos antes de mover la carga.", "Planifica el packaging y los insertos.", "Cómo preparar un brief de sourcing."}, FallbackBodies: []string{"Una lista clara para factura, bultos y el siguiente control aduanero.", "Mantén cajas, etiquetas e insertos dentro de la regla de preparación.", "Convierte enlace, cantidad y mercado en una petición lista para proveedor."}},
	"it": {Kicker: "DAL DESK FREIGHTVANTA", Title: "Conoscenze per muoversi meglio.", Body: "Guide pratiche su importazione, Incoterms, brief ai fornitori, scelta tra mare e aereo e decisioni tra ordine e consegna.", FeaturedLabel: "GUIDA IN EVIDENZA", FeaturedTitle: "Mare o aereo: scegliere il percorso giusto.", FeaturedBody: "Confronta disponibilità, profilo della merce, finestra obiettivo, documenti e passaggi prima di prenotare.", LatestLabel: "IN EVIDENZA · 8 MIN DI LETTURA", ReadLatest: "Leggi la guida", BrowseTopics: "Esplora gli argomenti", ExplainLabel: "COSA SPIEGHIAMO", MoreTitle: "Dal desk FreightVanta.", MoreBody: "Indicazioni pratiche sui dettagli tra “ordinato” e “consegnato”.", NewsletterKicker: "TENERE VICINA LA PROSSIMA DECISIONE", NewsletterTitle: "Una guida utile, una volta al mese.", NewsletterBody: "Note pratiche su sourcing dalla Cina, rotte, importazione e fulfillment. Niente rumore, solo il prossimo passaggio.", Subscribe: "Iscriviti", Topics: []string{"Tutte le risorse", "Pianificare l’import", "Sourcing", "Modalità di trasporto", "Fulfillment", "Packaging"}, FallbackTitles: []string{"Preparare i documenti prima della partenza.", "Pianificare packaging e inserti.", "Come preparare un brief di sourcing."}, FallbackBodies: []string{"Una checklist per fattura, colli e prossimo passaggio doganale.", "Tenere scatole, etichette e inserti nella stessa regola operativa.", "Trasformare link, quantità e mercato in una richiesta pronta."}},
	"nl": {Kicker: "VANUIT HET FREIGHTVANTA-TEAM", Title: "Kennis voor betere beslissingen.", Body: "Praktische uitleg over importvoorbereiding, Incoterms, leveranciersbriefings, zee- en luchtvracht en de stap tussen bestelling en levering.", FeaturedLabel: "UITGELICHTE GIDS", FeaturedTitle: "Zee of lucht: welke route past?", FeaturedBody: "Vergelijk gereedheid, vrachtprofiel, gewenste datum, documenten en overdrachten voordat u boekt.", LatestLabel: "UITGELICHT · 8 MIN LEZEN", ReadLatest: "Lees de gids", BrowseTopics: "Bekijk onderwerpen", ExplainLabel: "WAT WE UITLEGGEN", MoreTitle: "Meer vanuit het FreightVanta-team.", MoreBody: "Praktische notities over de details tussen “besteld” en “geleverd”.", NewsletterKicker: "HOUD DE VOLGENDE BESLISSING DICHTBIJ", NewsletterTitle: "Eén nuttige gids per maand.", NewsletterBody: "Ontvang praktische notities over sourcing uit China, routes, importvoorbereiding en fulfillment. Geen ruis, alleen de volgende beslissing.", Subscribe: "Abonneren", Topics: []string{"Alle kennis", "Import plannen", "Sourcing", "Vrachtmodi", "Fulfillment", "Verpakking"}, FallbackTitles: []string{"Documenten voorbereiden voordat de vracht vertrekt.", "Verpakking en inserts plannen.", "Een goede sourcingbrief maken."}, FallbackBodies: []string{"Een praktische lijst voor factuur, colli en de volgende douaneoverdracht.", "Houd dozen, labels en inserts bij dezelfde voorbereidingsregel.", "Maak van link, aantallen en markt een duidelijke leveranciersvraag."}},
}

func guideIndexCopyFor(locale string) publicGuideIndexCopy {
	code := strings.ToLower(strings.Split(strings.TrimSpace(locale), "-")[0])
	if value, ok := guideIndexCopies[code]; ok {
		return value
	}
	return guideIndexCopies["en"]
}

var homeTrustItems = map[string][]string{
	"en": {"Express", "Air freight", "Ocean freight", "Customs", "Warehousing", "Last mile"},
	"de": {"Express", "Luftfracht", "Seefracht", "Zoll", "Lager", "Letzte Meile"},
	"fr": {"Express", "Aérien", "Maritime", "Douane", "Stockage", "Dernier kilomètre"},
	"es": {"Express", "Aéreo", "Marítimo", "Aduanas", "Almacén", "Último tramo"},
	"it": {"Express", "Aereo", "Marittimo", "Dogana", "Magazzino", "Ultimo miglio"},
	"nl": {"Express", "Luchtvracht", "Zeevracht", "Douane", "Opslag", "Laatste kilometer"},
}

type homeSectionText struct {
	Title string
	Body  string
}

type homeProcessText struct {
	Title string
	Body  string
	Steps []publicProcessStep
}

type homeIndustryText struct {
	Title string
	Body  string
	Items []publicIndustryItem
}

type homeFAQText struct {
	Title string
	Items []publicFAQItem
}

var homeServices = map[string][]publicServiceItem{
	"en": {
		{Label: "PRODUCT SOURCING", Title: "Find the right product path.", Body: "Share a product link, photo, specification or target cost. Our team can help identify suitable China suppliers, compare options and organize samples or purchasing details before you commit to a shipment.", LinkLabel: "See product sourcing →"},
		{Label: "OCEAN FREIGHT", Title: "Plan the economical leg.", Body: "For consolidated or container freight, we help align cargo readiness, export documents, port handoffs and the delivery plan. The brief explains what is included, which decisions are still open and who owns each handoff.", LinkLabel: "See ocean freight →"},
		{Label: "AIR FREIGHT", Title: "Protect the time-sensitive leg.", Body: "When a launch, replenishment or urgent order cannot wait for the next ocean cycle, we compare practical air options and prepare the paperwork needed for a clean handoff.", LinkLabel: "See air freight →"},
		{Label: "CUSTOMS COORDINATION", Title: "Make documents ready early.", Body: "We help collect commercial invoices, packing details and shipment information so customs questions are found before the cargo reaches the next checkpoint. Final classification and compliance remain subject to the applicable authorities and your broker."},
		{Label: "WAREHOUSING & FULFILLMENT", Title: "Hold, check and dispatch with purpose.", Body: "Inventory can be received, checked, consolidated and prepared for delivery. We can remove supplier price tags, combine multi-item orders and follow the packing instructions agreed for your store."},
		{Label: "BRANDING & PRIVATE LABEL", Title: "Make the package feel like yours.", Body: "Coordinate inserts, stickers, hangtags, custom bags or boxes and other approved brand elements as part of the fulfillment brief. We confirm artwork, quantities and production steps before use."},
	},
	"de": {
		{Label: "PRODUKTBESCHAFFUNG", Title: "Lieferantenoptionen belastbar prüfen.", Body: "Senden Sie Link, Foto oder Spezifikation. Wir helfen, geeignete Lieferanten zu identifizieren, Varianten zu vergleichen und die nächsten Einkaufsfragen zu klären."},
		{Label: "SEEFRACHT", Title: "Kapazität und Übergaben sauber vorbereiten.", Body: "Für Sammel- oder Containerfracht stimmen wir Warenbereitschaft, Packdaten, Exportunterlagen und die Übergabe am Ziel ab. Offene Punkte bleiben sichtbar."},
		{Label: "LUFTFRACHT", Title: "Wenn der Termin die Route bestimmt.", Body: "Bei dringenden Nachlieferungen vergleichen wir geeignete Luftfrachtwege und bereiten die für die nächste Übergabe erforderlichen Informationen vor."},
		{Label: "ZOLLKOORDINATION", Title: "Dokumente früh auf Vollständigkeit prüfen.", Body: "Rechnungs-, Pack- und Produktangaben werden vor dem Versand strukturiert gesammelt. Tarifierung und Freigabe bleiben Sache der zuständigen Stelle oder Ihres Zollpartners."},
		{Label: "LAGERUNG & FULFILLMENT", Title: "Prüfen, bündeln, versenden.", Body: "Waren können angenommen, kontrolliert, zusammengeführt und gemäß Ihrer Versandvorgabe vorbereitet werden. Mehrteilige Bestellungen und neutrale Pakete lassen sich im Prozess abbilden."},
		{Label: "VERPACKUNG & BRANDING", Title: "Verpackung passend zur Marke umsetzen.", Body: "Beileger, Aufkleber, Hangtags, Beutel oder Kartons werden nach freigegebenem Artwork und vereinbarter Stückzahl vorbereitet."},
	},
	"fr": {
		{Label: "SOURCING EN CHINE", Title: "Partir du bon produit.", Body: "Envoyez un lien, une photo ou une fiche. Notre équipe peut rechercher des fournisseurs adaptés en Chine, comparer les options et préparer les questions d’échantillonnage ou d’achat.", LinkLabel: "Découvrir le sourcing en Chine"},
		{Label: "FRET MARITIME", Title: "Donner du rythme au volume.", Body: "Pour le groupage ou le conteneur, nous alignons disponibilité, préparation, informations d’expédition et relais jusqu’à la destination prévue.", LinkLabel: "Découvrir le fret maritime"},
		{Label: "FRET AÉRIEN", Title: "Protéger une échéance importante.", Body: "Pour une relance, un lancement ou une commande urgente, nous étudions un chemin aérien cohérent avec le produit et les documents disponibles.", LinkLabel: "Découvrir le fret aérien"},
		{Label: "COORDINATION DOUANIÈRE", Title: "Préparer les documents avant le départ.", Body: "Facture, colisage et données produit sont rassemblés au même endroit. La classification et le dédouanement restent soumis à votre courtier et aux autorités compétentes.", LinkLabel: "Découvrir la coordination douanière"},
		{Label: "ENTREPOSAGE ET LOGISTIQUE E-COMMERCE", Title: "Contrôler avant de remettre en mouvement.", Body: "Réception, contrôle, regroupement, emballage et expédition peuvent suivre une seule consigne. Les commandes multi-articles et les colis neutres sont traités selon le brief approuvé.", LinkLabel: "Découvrir l’entreposage"},
		{Label: "EMBALLAGE ET IMAGE DE MARQUE", Title: "Faire arriver votre marque avec le produit.", Body: "Cartes, stickers, étiquettes, sacs ou boîtes personnalisés sont préparés après validation du visuel, de la quantité et de la séquence de production.", LinkLabel: "Découvrir l’emballage et l’image de marque"},
	},
	"es": {
		{Label: "PROVEEDORES EN CHINA", Title: "Encuentra una opción viable.", Body: "Comparte un enlace, una foto o una ficha. Ayudamos a buscar proveedores en China, comparar alternativas y preparar muestras o preguntas de compra.", LinkLabel: "Ver búsqueda de proveedores →"},
		{Label: "TRANSPORTE MARÍTIMO", Title: "Mueve volumen con un plan.", Body: "Alineamos disponibilidad de la mercancía, preparación, datos de bultos, salida y entrega para carga consolidada o contenedor, según el caso.", LinkLabel: "Ver transporte marítimo →"},
		{Label: "TRANSPORTE AÉREO", Title: "Cuando la fecha importa.", Body: "Para reposiciones, lanzamientos o pedidos urgentes, revisamos una alternativa aérea práctica y los datos que deben acompañarla.", LinkLabel: "Ver transporte aéreo →"},
		{Label: "COORDINACIÓN ADUANERA", Title: "Menos sorpresas en el siguiente control.", Body: "Organizamos factura, packing list y datos del producto antes de la salida. La clasificación y el despacho dependen del agente y de las autoridades correspondientes.", LinkLabel: "Ver coordinación aduanera →"},
		{Label: "ALMACENAJE Y E-COMMERCE", Title: "Recibir, revisar y preparar.", Body: "Gestiona recepción, control, consolidación y preparación de pedidos con una instrucción única. Podemos mantener paquetes neutros y pedidos con varios artículos según el brief.", LinkLabel: "Ver almacenaje →"},
		{Label: "EMBALAJE Y MARCA", Title: "Que el paquete también hable de tu marca.", Body: "Coordina tarjetas, pegatinas, etiquetas, bolsas o cajas personalizadas tras aprobar diseño, cantidad y orden de producción.", LinkLabel: "Ver embalaje y marca →"},
	},
	"it": {
		{Label: "FORNITORI IN CINA", Title: "Iniziare dal prodotto giusto.", Body: "Invia link, foto o specifiche. Possiamo cercare fornitori in Cina, confrontare alternative e preparare campioni o domande d’acquisto.", LinkLabel: "Scopri la ricerca fornitori"},
		{Label: "TRASPORTO MARITTIMO", Title: "Dare struttura al volume.", Body: "Per groupage o container coordiniamo disponibilità, preparazione, dati di imballo, partenza e consegna prevista.", LinkLabel: "Scopri il trasporto marittimo"},
		{Label: "TRASPORTO AEREO", Title: "Proteggere un momento importante.", Body: "Per lanci, riassortimenti o urgenze valutiamo un percorso aereo coerente con prodotto, documenti e priorità.", LinkLabel: "Scopri il trasporto aereo"},
		{Label: "COORDINAMENTO DOGANALE", Title: "Preparare prima di spedire.", Body: "Fattura, packing list e informazioni prodotto restano raccolte in modo ordinato. Classificazione e sdoganamento dipendono dal broker e dalle autorità competenti.", LinkLabel: "Scopri il coordinamento doganale"},
		{Label: "MAGAZZINO ED E-COMMERCE", Title: "Ricevere, controllare, preparare.", Body: "Ricezione, verifica, consolidamento, imballo e invio seguono una stessa istruzione approvata. Gli ordini con più articoli e i pacchi neutri rientrano nel brief.", LinkLabel: "Scopri il magazzino"},
		{Label: "IMBALLAGGIO E BRAND", Title: "Portare la tua identità nel pacco.", Body: "Cartoline, adesivi, etichette, buste o scatole personalizzate vengono gestiti dopo l’approvazione di grafica, quantità e sequenza produttiva.", LinkLabel: "Scopri imballaggio e brand"},
	},
	"nl": {
		{Label: "PRODUCTSOURCING", Title: "Een leverancier die bij de vraag past.", Body: "Stuur een link, foto of specificatie. We kunnen leveranciers in China zoeken, opties naast elkaar zetten en vragen over sample of aankoop voorbereiden.", LinkLabel: "Bekijk productsourcing"},
		{Label: "ZEEVRACHT", Title: "Volume met overzicht.", Body: "Voor groupage of container stemmen we gereedheid, verpakkingsgegevens, vertrek en overdracht naar de bestemming op elkaar af.", LinkLabel: "Bekijk zeevracht"},
		{Label: "LUCHTVRACHT", Title: "Een route voor tijdkritische goederen.", Body: "Voor lanceringen, aanvulling of spoed bekijken we een praktische luchtvrachtoptie en de informatie die voor de overdracht nodig is.", LinkLabel: "Bekijk luchtvracht"},
		{Label: "DOUANECOÖRDINATIE", Title: "Informatie klaar vóór vertrek.", Body: "Factuur, paklijst en productgegevens worden gestructureerd verzameld. Classificatie en inklaring blijven afhankelijk van uw broker en de bevoegde autoriteiten.", LinkLabel: "Bekijk douanecoördinatie"},
		{Label: "OPSLAG & FULFILMENT", Title: "Ontvangen, controleren, doorzetten.", Body: "Goederen kunnen worden ontvangen, gecontroleerd, samengevoegd en volgens uw verzendinstructie klaargemaakt. Neutrale verpakking en orders met meerdere artikelen passen in dezelfde workflow.", LinkLabel: "Bekijk opslag en fulfilment"},
		{Label: "VERPAKKING & BRANDING", Title: "Uw merk meegeven aan de laatste meter.", Body: "Inserts, stickers, labels, tassen of dozen worden voorbereid na goedkeuring van ontwerp, aantallen en productiestappen.", LinkLabel: "Bekijk verpakking en branding"},
	},
}

var homeAdvantages = map[string]struct {
	Title string
	Items []publicAdvantageItem
}{
	"en": {Title: "The details are where reliability is built.", Items: []publicAdvantageItem{{Title: "A named point of contact", Body: "One person keeps the request, supplier questions and fulfillment notes in the same thread."}, {Title: "Quality checks before dispatch", Body: "Confirm product condition, quantity and agreed packaging instructions before goods leave the facility."}, {Title: "Flexible shipment preparation", Body: "Consolidate orders, separate destinations or hold inventory according to the plan you approve."}, {Title: "Trackable handoffs", Body: "Keep carrier references and status notes together so your team knows what changed and what happens next."}}},
	"de": {Title: "Verlässlichkeit entsteht durch dokumentierte Details.", Items: []publicAdvantageItem{{Title: "Fester Ansprechpartner", Body: "Fragen, Lieferantenantworten und Versandnotizen bleiben in einem Vorgang."}, {Title: "Qualitätsprüfung vor Versand", Body: "Zustand, Menge und vereinbarte Verpackung werden vor dem nächsten Übergang geprüft."}, {Title: "Klare Verantwortlichkeiten", Body: "Jede Übergabe erhält einen Status, eine zuständige Person und den nächsten Schritt."}, {Title: "Ausnahmen früh melden", Body: "Änderungen werden markiert, damit Einkauf und Vertrieb reagieren können."}}},
	"fr": {Title: "La maîtrise se voit dans les transitions.", Items: []publicAdvantageItem{{Title: "Un fil de conversation", Body: "Les questions fournisseur et les décisions de transport restent rattachées au même dossier."}, {Title: "Un contrôle avant départ", Body: "État, quantité et présentation sont revus avant le prochain relais."}, {Title: "Une information lisible", Body: "Le statut explique ce qui est fait, ce qui manque et qui agit."}, {Title: "Une alerte utile", Body: "Lorsqu’un point change, votre équipe le voit assez tôt pour choisir."}}},
	"es": {Title: "El control está en los pequeños detalles.", Items: []publicAdvantageItem{{Title: "Un contacto que responde", Body: "Preguntas de proveedor, compras y envíos en el mismo hilo."}, {Title: "Revisión antes de salir", Body: "Estado, cantidad y presentación comprobados antes del siguiente relevo."}, {Title: "Estados que sirven", Body: "Cada actualización explica qué se hizo y qué toca ahora."}, {Title: "Avisos a tiempo", Body: "Los cambios aparecen antes de convertirse en una sorpresa para tus clientes."}}},
	"it": {Title: "La qualità si riconosce nei dettagli.", Items: []publicAdvantageItem{{Title: "Un riferimento personale", Body: "Domande, risposte dei fornitori e note di spedizione non si disperdono."}, {Title: "Controllo prima del movimento", Body: "Stato, quantità e presentazione verificati prima del passaggio successivo."}, {Title: "Ordine nelle informazioni", Body: "Ogni aggiornamento dice cosa è pronto e cosa va deciso."}, {Title: "Eccezioni raccontate bene", Body: "Una variazione diventa una scelta, non una sorpresa."}}},
	"nl": {Title: "Duidelijkheid bij elk knooppunt.", Items: []publicAdvantageItem{{Title: "Eén aanspreekpunt", Body: "Sourcingvragen, leveranciersreacties en verzendnotities blijven gekoppeld."}, {Title: "Controle vóór vertrek", Body: "Staat, aantallen en afgesproken verpakking worden gecontroleerd."}, {Title: "Status met betekenis", Body: "Iedere update maakt duidelijk wat gereed is en wat nu nodig is."}, {Title: "Uitzonderingen zichtbaar", Body: "Een wijziging komt vroeg genoeg in beeld om voorraad en klantcommunicatie aan te passen."}}},
}

var homeProcess = map[string]homeProcessText{
	"en": {Title: "A practical process for complex freight.", Body: "If an assumption changes, the plan should show the change instead of hiding it in a long email chain.", Steps: []publicProcessStep{{Title: "Tell us what is moving", Body: "Product links, quantities, destination, target date and any packaging or compliance needs."}, {Title: "Review the plan", Body: "We clarify the service path, open questions, documents and responsibilities before work starts."}, {Title: "Coordinate every handoff", Body: "Sourcing, purchase, inspection, preparation, transport and delivery updates follow one record."}, {Title: "Keep your customer promise", Body: "Receive the tracking and exception notes needed to plan inventory and customer communication."}}},
	"de": {Title: "Vier Schritte, die Entscheidungen leichter machen.", Body: "Ändert sich eine Annahme, soll der Plan die Änderung zeigen – statt sie in einer langen E-Mail-Kette zu verstecken.", Steps: []publicProcessStep{{Title: "Anforderungen aufnehmen", Body: "Produkt, Menge, Ziel, Termin, Dokumente und Verpackungswünsche."}, {Title: "Vorgehen festlegen", Body: "Leistungsumfang, offene Fragen und Zuständigkeiten bestätigen."}, {Title: "Übergaben koordinieren", Body: "Beschaffung, Prüfung, Verpackung, Transport und Zustellung fortlaufend dokumentieren."}, {Title: "Ankunft vorbereiten", Body: "Tracking und Ausnahmehinweise so übergeben, dass Ihr Team planen kann."}}},
	"fr": {Title: "De la première question à la bonne réception.", Body: "Une bonne livraison est une suite de petites décisions bien prises. Nous les rassemblons pour que votre équipe puisse avancer sereinement.", Steps: []publicProcessStep{{Title: "Comprendre", Body: "Produit, volume, origine, destination, date cible et contraintes."}, {Title: "Proposer", Body: "Chemin de service, documents à réunir, responsabilités et questions ouvertes."}, {Title: "Coordonner", Body: "Fournisseur, contrôle, emballage, transport, stockage et remise au dernier relais."}, {Title: "Accompagner", Body: "Tracking et notes d’exception pour préparer la suite avec vos clients ou vos équipes."}}},
	"es": {Title: "Cuatro pasos para moverlo mejor.", Body: "No necesitas perseguir a cada proveedor y transportista por separado. Reunimos la información necesaria y conectamos los relevos.", Steps: []publicProcessStep{{Title: "Cuéntanos qué mueves", Body: "Producto, cantidad, origen, destino, fecha y requisitos."}, {Title: "Recibe un plan útil", Body: "Alcance, documentos, responsables y preguntas abiertas."}, {Title: "Coordinamos cada entrega", Body: "Proveedor, inspección, embalaje, transporte, almacén y último tramo."}, {Title: "Sigue el envío hasta llegar", Body: "Tracking y excepciones para que puedas informar y decidir."}}},
	"it": {Title: "Quattro gesti, un flusso continuo.", Body: "Una consegna ben fatta nasce prima della partenza. Mettiamo in ordine le informazioni che servono a ogni passaggio.", Steps: []publicProcessStep{{Title: "Capire la merce", Body: "Prodotto, quantità, origine, destinazione, data e vincoli."}, {Title: "Costruire il piano", Body: "Percorso, documenti, responsabilità e domande aperte."}, {Title: "Coordinare i passaggi", Body: "Fornitore, controllo, packaging, trasporto, magazzino e ultimo miglio."}, {Title: "Restare aggiornati", Body: "Tracking e note di eccezione per organizzare clienti e stock."}}},
	"nl": {Title: "Van eerste vraag naar bevestigde aankomst.", Body: "Elke extra overdracht is een kans op vertraging of misverstanden. Daarom verzamelen we de juiste informatie vóór het volgende knooppunt.", Steps: []publicProcessStep{{Title: "Vertel wat u vervoert", Body: "Product, hoeveelheid, oorsprong, bestemming, datum en voorwaarden."}, {Title: "Ontvang een praktisch plan", Body: "Route, documenten, eigenaars en open vragen."}, {Title: "Coördineer iedere overdracht", Body: "Leverancier, controle, verpakking, transport, opslag en laatste kilometer."}, {Title: "Blijf op de hoogte", Body: "Tracking en uitzonderingsnotities voor uw volgende beslissing."}}},
}

var homeIndustries = map[string]homeIndustryText{
	"en": {Title: "Built for teams that have something to lose in the handoff.", Items: []publicIndustryItem{{Title: "Ecommerce & retail", Body: "Keep replenishment, bundles and store-specific packaging organized."}, {Title: "Consumer goods", Body: "Coordinate product details, quality checks and presentation from supplier to shelf."}, {Title: "Industrial components", Body: "Work from specifications, documentation and a clear receiving plan."}, {Title: "Time-critical cargo", Body: "Prioritize the next feasible movement and make exceptions visible early."}}},
	"de": {Title: "Für Waren, bei denen Genauigkeit zählt.", Body: "Unterschiedliche Waren brauchen unterschiedliche Prüfungen, Unterlagen und Zustellgespräche. Die Arbeit beginnt bei der Anforderung, die für Ihren Betrieb am meisten zählt.", Items: []publicIndustryItem{{Title: "Maschinen- und Industriekomponenten", Body: "Spezifikationen, Packdaten und Empfangsvorgaben im Vordergrund."}, {Title: "E-Commerce & Handel", Body: "Nachbestellungen, Bundles und neutrale Markenverpackung koordinieren."}, {Title: "Konsumgüter", Body: "Produktqualität, Präsentation und planbare Übergaben verbinden."}, {Title: "Terminsensible Sendungen", Body: "Nächste realistische Option und offene Risiken früh sichtbar machen."}}},
	"fr": {Title: "Une attention adaptée à chaque activité.", Body: "Des marchandises différentes exigent des contrôles, des documents et des conversations de livraison différents. Le travail commence par la contrainte qui compte le plus pour votre activité.", Items: []publicIndustryItem{{Title: "E-commerce & retail", Body: "Réassorts, bundles et expérience colis cohérente."}, {Title: "Biens de consommation", Body: "Qualité, présentation et informations produit alignées."}, {Title: "Industrie & composants", Body: "Spécifications, documents et réception maîtrisés."}, {Title: "Fret urgent", Body: "Décision rapide, scénario lisible et risques explicités."}}},
	"es": {Title: "Logística para negocios que no se detienen.", Body: "Cada tipo de mercancía necesita sus propios controles, documentos y conversaciones de entrega. El trabajo empieza por la restricción que más importa a su operación.", Items: []publicIndustryItem{{Title: "E-commerce y retail", Body: "Reposiciones, bundles y preparación coherente para cada pedido."}, {Title: "Bienes de consumo", Body: "Producto, calidad y experiencia de entrega en una misma conversación."}, {Title: "Industria y componentes", Body: "Especificaciones, documentos y recepción ordenada."}, {Title: "Carga urgente", Body: "Una alternativa realista y riesgos visibles desde el principio."}}},
	"it": {Title: "Ritmi diversi, stessa cura.", Body: "Merci diverse richiedono controlli, documenti e conversazioni di consegna diversi. Il lavoro parte dal vincolo che conta di più per la sua operatività.", Items: []publicIndustryItem{{Title: "E-commerce e retail", Body: "Riassortimenti, bundle e presentazione coerente."}, {Title: "Moda, casa e beni di consumo", Body: "Qualità, packaging e consegna come parte della marca."}, {Title: "Industria e componenti", Body: "Specifiche, documenti e ricezione controllata."}, {Title: "Carichi urgenti", Body: "Priorità chiara e scenario realistico."}}},
	"nl": {Title: "Logistiek die werkt zoals uw bedrijf werkt.", Body: "Verschillende goederen vragen om verschillende controles, documenten en leveringsgesprekken. Het werk begint bij de beperking die voor uw operatie het belangrijkst is.", Items: []publicIndustryItem{{Title: "E-commerce & retail", Body: "Herbevoorrading, bundels en een consistente orderverwerking."}, {Title: "Consumptiegoederen", Body: "Kwaliteit, verpakking en levering in één overzicht."}, {Title: "Industrie & componenten", Body: "Specificaties, documenten en ontvangstafspraken voorop."}, {Title: "Tijdkritische vracht", Body: "Realistische keuze, snelle signalering en duidelijke eigenaar."}}},
}

var homeFAQs = map[string]homeFAQText{
	"en": {Title: "Questions before you ship", Items: []publicFAQItem{{Question: "Can I start with only a product link?", Answer: "Yes. A link, photo or short specification is enough for an initial sourcing conversation; quantities and destination can follow."}, {Question: "Can you combine sourcing and fulfillment?", Answer: "The homepage should present them as one coordinated workflow, with the final scope confirmed in the shipment plan."}, {Question: "Do you provide customs clearance?", Answer: "We coordinate the information and handoffs; the site must identify the responsible broker and jurisdiction before making a clearance claim."}, {Question: "Can I request a single service?", Answer: "Yes. The form lets visitors select sourcing, transport, storage, branding, fulfillment or a combined plan."}}},
	"de": {Title: "Fragen vor dem Versand?", Items: []publicFAQItem{{Question: "Kann ich mit einem Produktlink starten?", Answer: "Ja. Link, Foto oder Spezifikation reichen für die erste Anfrage."}, {Question: "Planen Sie auch einzelne Leistungen?", Answer: "Ja. Das Formular lässt Beschaffung, Transport, Lager, Verpackung, Fulfillment oder eine Kombination auswählen."}, {Question: "Übernehmen Sie die Zollabfertigung?", Answer: "Wir koordinieren Angaben und Übergaben; die zuständige Abfertigungsstelle muss je Sendung bestätigt werden."}, {Question: "Welche Angaben beschleunigen die Antwort?", Answer: "Start, Ziel, Menge, gewünschter Termin, Produktart und vorhandene Dokumente."}}},
	"fr": {Title: "Des questions avant d’expédier ?", Items: []publicFAQItem{{Question: "Puis-je commencer avec une simple URL produit ?", Answer: "Oui. Un lien, une photo ou une courte fiche permet d’ouvrir l’échange."}, {Question: "Proposez-vous une seule étape ou un parcours complet ?", Answer: "Les deux : le formulaire permet de sélectionner sourcing, transport, stockage, marque, fulfilment ou une combinaison."}, {Question: "Gérez-vous le dédouanement ?", Answer: "Nous préparons les informations et les relais ; le courtier et la juridiction doivent être confirmés pour chaque dossier."}, {Question: "Que faut-il indiquer dans la demande ?", Answer: "Origine, destination, quantité, produit, échéance souhaitée et documents déjà disponibles."}}},
	"es": {Title: "¿Dudas antes de enviar?", Items: []publicFAQItem{{Question: "¿Puedo empezar con un enlace de producto?", Answer: "Sí. Un enlace, foto o descripción corta es suficiente para iniciar."}, {Question: "¿Puedo contratar solo una parte?", Answer: "Sí. El formulario permite seleccionar sourcing, transporte, almacén, packaging, fulfillment o un plan combinado."}, {Question: "¿Incluye despacho de aduanas?", Answer: "Coordinamos información y relevos; el agente responsable debe confirmarse para cada operación."}, {Question: "¿Qué datos aceleran la respuesta?", Answer: "Producto, cantidad, origen, destino, fecha objetivo y documentos disponibles."}}},
	"it": {Title: "Dubbi prima di spedire?", Items: []publicFAQItem{{Question: "Posso iniziare da un semplice link?", Answer: "Sì. Un link, una foto o una breve scheda aprono la conversazione."}, {Question: "Posso chiedere una sola soluzione?", Answer: "Sì. Il form permette di scegliere sourcing, trasporto, magazzino, packaging, fulfillment o un percorso completo."}, {Question: "Gestite lo sdoganamento?", Answer: "Organizziamo dati e passaggi; broker e autorità vanno confermati per ogni pratica."}, {Question: "Quali dati servono?", Answer: "Prodotto, quantità, origine, destinazione, data desiderata e documenti disponibili."}}},
	"nl": {Title: "Welke vragen spelen vóór de eerste overdracht?", Items: []publicFAQItem{{Question: "Kan ik met alleen een productlink beginnen?", Answer: "Ja. Een link, foto of korte specificatie is genoeg voor een eerste gesprek."}, {Question: "Kan ik één onderdeel aanvragen?", Answer: "Ja. Kies sourcing, transport, opslag, verpakking, fulfillment of een gecombineerde route."}, {Question: "Regelen jullie de inklaring?", Answer: "We coördineren gegevens en overdrachten; de verantwoordelijke broker moet per zending worden bevestigd."}, {Question: "Welke gegevens helpen het snelst?", Answer: "Product, hoeveelheid, vertrekpunt, bestemming, gewenste datum en beschikbare documenten."}}},
}

var publicCopies = map[string]publicCopy{
	"en": {
		LanguageName: "English", NavServices: "Solutions", NavIndustries: "Industries", NavProcess: "How it works", NavGuides: "Insights", NavAbout: "About", NavContact: "Contact", SwitchLabel: "Language",
		HeroKicker: "GLOBAL FREIGHT, CLEARLY MANAGED", HeroTitle: "Freight that keeps your business moving.", HeroBody: "From the first supplier conversation to the final delivery, FreightVanta coordinates the people, documents and handoffs behind your shipment. You get one practical plan, clear ownership and updates you can act on.", HeroPrimary: "Get a shipment plan", HeroSecondary: "Explore solutions →", HeroMicrocopy: "Tell us what is moving, where it starts and where it needs to arrive. We will come back with the right next step.",
		TrustLabel: "Built for international trade", TrustValue: "Clear routes · Local expertise · Trackable delivery",
		ServicesKicker: "WHAT WE COORDINATE", ServicesTitle: "One operating view from supplier to customer.", ServicesBody: "Your shipment rarely follows one simple step. We connect sourcing, preparation, transport, customs and delivery into a workflow your team can follow.",
		Service1Title: "Express delivery", Service1Body: "Time-sensitive parcels with dependable transit options and end-to-end tracking.", Service2Title: "Air & ocean freight", Service2Body: "Flexible capacity for commercial cargo, from urgent air freight to cost-efficient ocean routes.", Service3Title: "Customs support", Service3Body: "Documentation guidance that helps your goods cross borders with less friction.",
		GuidesKicker: "INSIGHTS", GuidesTitle: "Shipping intelligence for better decisions.", GuidesBody: "Practical guides for international freight, imports, Incoterms, supplier coordination and the decisions that sit between “ordered” and “delivered.”", GuidesLinks: []string{"Import planning checklist", "Ocean vs. air freight", "How to prepare a product sourcing brief", "Packaging and insert guide"}, ReadMore: "Read guide", NoGuides: "No guides are published in English yet.",
		ContactKicker: "REQUEST A SHIPMENT PLAN", ContactTitle: "Tell us what you need to move. We will turn the moving parts into a plan your team can use.", ContactBody: "Tell us what you need to move. We will turn the moving parts into a plan your team can use.", ContactButton: "Request a shipment plan", FooterNote: "FreightVanta summary · Solutions · Industries & Insights · Contact · Privacy · Terms.", PreviewNote: "Local preview · Search engines cannot index this page",
		MaintenanceTitle: "We will be back shortly.", MaintenanceBody: "This site is undergoing scheduled maintenance. Please try again soon.", NotFoundTitle: "This route could not be found.", NotFoundBody: "The page may have moved, or it has not been published in this language yet.", NotFoundButton: "Return to the homepage", ArticleBack: "Back to shipping guides", ArticleUpdated: "Updated", ArticlePublished: "Published", ArticleReading: "Reading time", ArticleMinute: "min", ArticleTags: "Topics", ArticleRelated: "More shipping guides",
	},
	"de": {
		LanguageName: "Deutsch", NavServices: "Leistungen", NavIndustries: "Branchen", NavProcess: "Prozess", NavGuides: "Wissen", NavAbout: "Über uns", NavContact: "Kontakt", SwitchLabel: "Sprache",
		HeroKicker: "INTERNATIONALE LOGISTIK, KLAR GEFÜHRT", HeroTitle: "Fracht zwischen. Klar. Sicher. Pünktlich geplant.", HeroBody: "FreightVanta koordiniert Beschaffung, Seefracht, Luftfracht, Zollinformationen, Lager und Fulfillment für internationale Lieferketten. Sie sehen, welche Entscheidung als Nächstes ansteht und wer sie verantwortet.", HeroPrimary: "Transport planen", HeroSecondary: "Leistungen ansehen", HeroMicrocopy: "Produkt, Menge, Start, Ziel und gewünschter Termin genügen für eine erste Einschätzung.",
		TrustLabel: "Leistungsübersicht", TrustValue: "Produktbeschaffung · Fracht · Lagerung · Fulfillment",
		ServicesKicker: "WAS WIR KOORDINIEREN", ServicesTitle: "Eine Lieferkette. Ein nachvollziehbarer Arbeitsstand.", ServicesBody: "Von der Anfrage bis zur Zustellung werden Informationen, Dokumente und Übergaben in einem abgestimmten Ablauf geführt.",
		Service1Title: "Expressversand", Service1Body: "Zeitkritische Pakete mit verlässlichen Laufzeiten und durchgängiger Sendungsverfolgung.", Service2Title: "Luft- und Seefracht", Service2Body: "Flexible Kapazitäten für Handelswaren – schnell per Luft oder wirtschaftlich per See.", Service3Title: "Zollunterstützung", Service3Body: "Praxisnahe Hilfe bei Dokumenten und Abläufen für reibungslosere Grenzprozesse.",
		GuidesKicker: "WISSEN", GuidesTitle: "Logistikwissen für sichere Entscheidungen.", GuidesBody: "Verständliche Leitfäden zu Importvorbereitung, Incoterms, Lieferantenbriefing, Seefracht oder Luftfracht und zur Prüfung von Packdaten.", GuidesLinks: []string{"Import-Checkliste", "Seefracht oder Luftfracht?", "Lieferantenbriefing", "Verpackung für den Direktversand"}, ReadMore: "Beitrag lesen", NoGuides: "Zurzeit sind noch keine deutschen Beiträge veröffentlicht.",
		ContactKicker: "TRANSPORT PLANEN", ContactTitle: "Beschreiben Sie Ihre Sendung. Wir ordnen die nächsten Schritte.", ContactBody: "Beginnen Sie mit Produkt, Menge, Start, Ziel und gewünschtem Termin. Eine Fachperson von FreightVanta prüft die Angaben und meldet sich mit dem passenden nächsten Schritt.", ContactButton: "Angebot anfordern", FooterNote: "Kurzprofil · Leistungen · Branchen · Wissen · Kontakt · Datenschutz · Impressum.", PreviewNote: "Lokale Vorschau · Diese Seite wird nicht indexiert",
		MaintenanceTitle: "Wir sind bald wieder für Sie da.", MaintenanceBody: "Diese Website wird derzeit gewartet. Bitte versuchen Sie es später erneut.", NotFoundTitle: "Diese Route wurde nicht gefunden.", NotFoundBody: "Die Seite wurde möglicherweise verschoben oder ist in dieser Sprache noch nicht veröffentlicht.", NotFoundButton: "Zur Startseite", ArticleBack: "Zurück zum Versandwissen", ArticleUpdated: "Aktualisiert", ArticlePublished: "Veröffentlicht", ArticleReading: "Lesezeit", ArticleMinute: "Min.", ArticleTags: "Themen", ArticleRelated: "Weitere Versandratgeber",
	},
	"fr": {
		LanguageName: "Français", NavServices: "Solutions", NavIndustries: "Secteurs", NavProcess: "Méthode", NavGuides: "Ressources", NavAbout: "À propos", NavContact: "Contact", SwitchLabel: "Langue",
		HeroKicker: "LE MOUVEMENT, AVEC UNE MÉTHODE", HeroTitle: "Une logistique qui vous suit, sans vous ralentir.", HeroBody: "Un fournisseur, un départ, plusieurs relais : FreightVanta relie l’approvisionnement, le transport, les documents, le stockage et la livraison dans un même fil de travail. Vous savez où en est votre marchandise et quelle décision vient ensuite.", HeroPrimary: "Échanger avec un expert", HeroSecondary: "Découvrir nos solutions", HeroMicrocopy: "Décrivez votre produit, son origine et sa destination. Nous commencerons par les questions qui comptent.",
		TrustLabel: "Nos domaines d’intervention", TrustValue: "Sourcing en Chine · Fret maritime · Fret aérien · Douane · Entreposage · Dernier kilomètre",
		ServicesKicker: "LES SAVOIR-FAIRE", ServicesTitle: "Des savoir-faire qui se complètent.", ServicesBody: "Une bonne livraison est une suite de petites décisions bien prises. Nous les rassemblons pour que votre équipe puisse avancer sereinement.",
		Service1Title: "Livraison express", Service1Body: "Des colis urgents, des délais fiables et un suivi de bout en bout.", Service2Title: "Fret aérien et maritime", Service2Body: "Des capacités flexibles pour le fret commercial, urgent par avion ou optimisé par mer.", Service3Title: "Assistance douanière", Service3Body: "Des conseils documentaires pour faciliter le passage de vos marchandises aux frontières.",
		GuidesKicker: "RESSOURCES", GuidesTitle: "Des ressources pour décider avec justesse.", GuidesBody: "Guides pratiques sur l’import, les Incoterms, le brief fournisseur, la différence entre maritime et aérien, et les contrôles à prévoir avant expédition.", GuidesLinks: []string{"Préparer un import", "Choisir maritime ou aérien", "Brief fournisseur", "Emballage et inserts"}, ReadMore: "Lire le guide", NoGuides: "Aucun guide en français n'est publié pour le moment.",
		ContactKicker: "PARLER À UN EXPERT", ContactTitle: "Votre prochaine expédition mérite mieux qu’une suite d’e-mails. Parlons-en et construisons un plan lisible.", ContactBody: "Décrivez votre produit, son origine et sa destination. Un spécialiste FreightVanta examine les détails et revient vers vous avec la prochaine étape adaptée.", ContactButton: "Demander un échange", FooterNote: "FreightVanta · Solutions · Secteurs · Ressources · Contact · Confidentialité · Mentions légales.", PreviewNote: "Aperçu local · Cette page ne peut pas être indexée",
		MaintenanceTitle: "Nous revenons très bientôt.", MaintenanceBody: "Ce site est en maintenance programmée. Merci de réessayer plus tard.", NotFoundTitle: "Cette page est introuvable.", NotFoundBody: "La page a peut-être été déplacée ou n'est pas encore publiée dans cette langue.", NotFoundButton: "Retour à l'accueil", ArticleBack: "Retour aux guides", ArticleUpdated: "Mis à jour", ArticlePublished: "Publié", ArticleReading: "Temps de lecture", ArticleMinute: "min", ArticleTags: "Sujets", ArticleRelated: "Autres guides d'expédition",
	},
	"es": {
		LanguageName: "Español", NavServices: "Soluciones", NavIndustries: "Sectores", NavProcess: "Método", NavGuides: "Guías", NavAbout: "Nosotros", NavContact: "Contacto", SwitchLabel: "Idioma",
		HeroKicker: "CARGA EN MOVIMIENTO. NEGOCIO EN MARCHA.", HeroTitle: "De origen a destino, sin perder el control.", HeroBody: "FreightVanta coordina proveedores, preparación, transporte, documentación, almacén y entrega para que cada paso de tu cadena logística tenga un responsable y una siguiente acción clara.", HeroPrimary: "Planificar un envío", HeroSecondary: "Ver soluciones", HeroMicrocopy: "Cuéntanos qué mueves, desde dónde sale y a dónde debe llegar. Empezamos con un plan que puedas revisar.",
		TrustLabel: "HOJA DE RUTA", TrustValue: "Proveedor en China · Mar, aire o ferrocarril · Aduana, stock y preparación · Entrega confirmada",
		ServicesKicker: "SOLUCIONES", ServicesTitle: "Una cadena coordinada para que tu negocio no se detenga.", ServicesBody: "No necesitas perseguir a cada proveedor y transportista por separado. Reunimos la información necesaria y conectamos los relevos.",
		Service1Title: "Entrega exprés", Service1Body: "Paquetes urgentes con opciones de tránsito fiables y seguimiento completo.", Service2Title: "Carga aérea y marítima", Service2Body: "Capacidad flexible para mercancía comercial, urgente por aire o eficiente por mar.", Service3Title: "Gestión aduanera", Service3Body: "Orientación documental para facilitar el paso de tus mercancías por frontera.",
		GuidesKicker: "RECURSOS", GuidesTitle: "Información para tomar mejores decisiones.", GuidesBody: "Guías prácticas sobre importación, Incoterms, brief de proveedores, transporte marítimo frente a aéreo y control de embalaje.", GuidesLinks: []string{"Checklist de importación", "Marítimo o aéreo", "Brief para proveedores", "Packaging para ecommerce"}, ReadMore: "Leer la guía", NoGuides: "Estamos preparando nuevas guías.",
		ContactKicker: "PLANIFICAR UN ENVÍO", ContactTitle: "Dinos qué necesitas mover. Convertimos cada paso en una ruta que puedas seguir.", ContactBody: "Empieza por el producto, la ruta o el resultado de entrega que necesitas. Un especialista de FreightVanta revisará los detalles y te propondrá el siguiente paso adecuado.", ContactButton: "Solicitar un plan", FooterNote: "FreightVanta · Soluciones · Sectores · Recursos · Contacto · Privacidad · Aviso legal.", PreviewNote: "Vista previa local · Esta página no será indexada",
		MaintenanceTitle: "Volveremos en breve.", MaintenanceBody: "El sitio está en mantenimiento programado. Inténtalo de nuevo más tarde.", NotFoundTitle: "No hemos encontrado esta ruta.", NotFoundBody: "Es posible que la página se haya movido o que aún no esté publicada en este idioma.", NotFoundButton: "Volver al inicio", ArticleBack: "Volver a las guías", ArticleUpdated: "Actualizado", ArticlePublished: "Publicado", ArticleReading: "Tiempo de lectura", ArticleMinute: "min", ArticleTags: "Temas", ArticleRelated: "Más guías de envío",
	},
	"it": {
		LanguageName: "Italiano", NavServices: "Soluzioni", NavIndustries: "Settori", NavProcess: "Il metodo", NavGuides: "Risorse", NavAbout: "Chi siamo", NavContact: "Contatti", SwitchLabel: "Lingua",
		HeroKicker: "MOVIMENTO, CURATO IN OGNI PASSAGGIO", HeroTitle: "Una filiera che lavora bene, dall’origine alla consegna.", HeroBody: "FreightVanta unisce ricerca prodotto, acquisto, controllo, preparazione, trasporto, magazzino e consegna in un percorso leggibile. Il tuo team sa cosa è stato fatto, cosa manca e quale decisione viene dopo.", HeroPrimary: "Parla con un esperto", HeroSecondary: "Scopri le soluzioni", HeroMicrocopy: "Raccontaci il prodotto, il punto di partenza e la destinazione. Costruiamo il primo passaggio insieme.",
		TrustLabel: "IL NOSTRO AMBITO DI LAVORO", TrustValue: "Ricerca fornitori in Cina · Trasporto marittimo · Trasporto aereo · Coordinamento doganale · Magazzino e logistica e-commerce · Consegna ultimo miglio",
		ServicesKicker: "SOLUZIONI COORDINATE", ServicesTitle: "Una catena pensata con cura.", ServicesBody: "Una consegna ben fatta nasce prima della partenza. Mettiamo in ordine le informazioni che servono a ogni passaggio.",
		Service1Title: "Consegna espressa", Service1Body: "Pacchi urgenti con tempi affidabili e tracciamento completo.", Service2Title: "Trasporto aereo e marittimo", Service2Body: "Capacità flessibile per merci commerciali, urgente via aerea o conveniente via mare.", Service3Title: "Assistenza doganale", Service3Body: "Supporto documentale per rendere più semplice il passaggio delle merci alla frontiera.",
		GuidesKicker: "RISORSE", GuidesTitle: "Conoscenze per muoversi meglio.", GuidesBody: "Guide pratiche su importazione, Incoterms, brief ai fornitori, scelta tra mare e aereo e controllo dell’imballo.", GuidesLinks: []string{"Checklist import", "Mare o aereo?", "Brief al fornitore", "Packaging per la consegna diretta"}, ReadMore: "Leggi la guida", NoGuides: "Non ci sono ancora guide pubblicate in italiano.",
		ContactKicker: "PARLA CON UN ESPERTO", ContactTitle: "La tua prossima spedizione merita un flusso comprensibile.", ContactBody: "Raccontaci il prodotto, il punto di partenza e la destinazione. Uno specialista FreightVanta esaminerà i dettagli e le proporrà il passo successivo adatto.", ContactButton: "Richiedi un piano", FooterNote: "FreightVanta · Soluzioni · Settori · Risorse · Contatti · Privacy · Note legali.", PreviewNote: "Anteprima locale · Questa pagina non verrà indicizzata",
		MaintenanceTitle: "Torniamo presto.", MaintenanceBody: "Il sito è in manutenzione programmata. Riprova più tardi.", NotFoundTitle: "Questa pagina non è stata trovata.", NotFoundBody: "La pagina potrebbe essere stata spostata o non è ancora pubblicata in questa lingua.", NotFoundButton: "Torna alla home", ArticleBack: "Torna alle guide", ArticleUpdated: "Aggiornato", ArticlePublished: "Pubblicato", ArticleReading: "Tempo di lettura", ArticleMinute: "min", ArticleTags: "Argomenti", ArticleRelated: "Altre guide alle spedizioni",
	},
	"nl": {
		LanguageName: "Nederlands", NavServices: "Diensten", NavIndustries: "Sectoren", NavProcess: "Proces", NavGuides: "Bronnen", NavAbout: "Over ons", NavContact: "Contact", SwitchLabel: "Taal",
		HeroKicker: "ROUTE CONTROL / ORIGIN → PORT → WAREHOUSE → CUSTOMER", HeroTitle: "Vracht, helder geregeld.", HeroBody: "FreightVanta brengt leverancier, voorbereiding, transport, documentatie, opslag en levering samen in één werkbare route. U ziet welke overdracht klaar is, wat aandacht vraagt en wie de volgende stap beheert.", HeroPrimary: "Plan uw zending", HeroSecondary: "Bekijk oplossingen", HeroMicrocopy: "Deel product, vertrekpunt, bestemming en gewenste datum. Wij zetten de losse schakels om in een overzichtelijk plan.",
		TrustLabel: "ONS WERKGEBIED", TrustValue: "Productsourcing in China · Zeevracht · Luchtvracht · Douanecoördinatie · Opslag & fulfilment · Last-milebezorging",
		ServicesKicker: "OPLOSSINGEN PER OVERDRACHT", ServicesTitle: "Eén route voor uw volledige keten.", ServicesBody: "Elke extra overdracht is een kans op vertraging of misverstanden. Daarom verzamelen we de juiste informatie vóór het volgende knooppunt.",
		Services: []publicServiceItem{
			{Label: "Productsourcing", Title: "Vind de juiste productroute.", Body: "Deel een productlink, een foto, een specificatie of een richtprijs. Wij helpen bij het ordenen van leveranciersvragen, vergelijkingspunten, monsters en inkoopdetails die vóór de volgende overdracht duidelijk moeten zijn.", LinkLabel: "Bekijk productsourcing"},
			{Label: "Zeevracht", Title: "Plan het voordelige traject.", Body: "Bij geconsolideerde of containervracht helpen wij de gereedheid van de lading, exportdocumenten, overdrachten in de haven en het leverplan op elkaar af te stemmen. De samenvatting toont wat is inbegrepen, welke beslissingen nog openstaan en wie de volgende stap zet.", LinkLabel: "Bekijk zeevracht"},
			{Label: "Luchtvracht", Title: "Bescherm het urgente traject.", Body: "Wanneer een lancering, een aanvulling of een spoedorder niet kan wachten op de volgende zeecyclus, vergelijken wij realistische luchtvrachtopties en organiseren wij de ophaling, verzenddocumenten en overdrachten bij levering.", LinkLabel: "Bekijk luchtvracht"},
			{Label: "Douanecoördinatie", Title: "Zorg dat documenten op tijd klaar zijn.", Body: "Wij helpen bij het verzamelen van commerciële facturen, paklijsten en zendingsinformatie, zodat vragen zichtbaar worden voordat de lading het volgende controlepunt bereikt.", LinkLabel: "Bekijk douanecoördinatie"},
			{Label: "Opslag & fulfilment", Title: "Ontvang, controleer en verzend met een doel.", Body: "Voorraad kan worden ontvangen, gecontroleerd, geconsolideerd, opgeslagen en voorbereid voor de bestemming die u goedkeurt. De samenvatting houdt product-, verpakkings- en vrijgave-instructies bij de order.", LinkLabel: "Bekijk opslag en fulfilment"},
			{Label: "Verpakking & branding", Title: "Maak van het pakket úw pakket.", Body: "Coördineer goedgekeurde inserts, stickers, hangtags, zakken, dozen en andere merkelementen als onderdeel van de fulfilmentsamenvatting.", LinkLabel: "Bekijk verpakking en branding"},
		},
		AdvantagesTitle: "Betrouwbaarheid zit in de details.",
		Advantages: []publicAdvantageItem{
			{Title: "Een vast aanspreekpunt", Body: "Eén persoon houdt de aanvraag, leveranciersvragen, notities bij de zending en de volgende actie in dezelfde werkdraad bij elkaar."},
			{Title: "Controles vóór verzending", Body: "Staat van het product, aantallen en afgesproken verpakkingsinstructies worden bevestigd voordat goederen de locatie verlaten."},
			{Title: "Flexibele voorbereiding", Body: "Consolideer orders, splits bestemmingen of houd voorraad aan volgens het plan dat uw team goedkeurt."},
			{Title: "Traceerbare overdrachten", Body: "Vervoerdersreferenties en statusnotities blijven bij elkaar, zodat uw team ziet wat er is veranderd en wat er daarna gebeurt."},
		},
		ProcessTitle: "Een praktisch proces voor complexe vracht.", ProcessBody: "Het gaat er niet om logistiek eenvoudig te laten lijken. Het gaat erom de volgende beslissing, het volgende document en de volgende overdracht zichtbaar te houden voordat ze een vertraging worden.",
		ProcessSteps: []publicProcessStep{
			{Marker: "01", Title: "Vertel ons wat er beweegt.", Body: "Deel productlinks, aantallen, herkomst, bestemming, gewenste datum en eventuele verpakkings- of compliance-eisen."},
			{Marker: "02", Title: "Beoordeel het plan.", Body: "Wij verduidelijken de voorgestelde route, open vragen, benodigde documenten en verantwoordelijkheden voordat het werk begint."},
			{Marker: "03", Title: "Wij coördineren elke overdracht.", Body: "Sourcing, inkoop, inspectie, voorbereiding, transport, opslag en levering volgen één werkdossier."},
			{Marker: "04", Title: "Kom uw klantbelofte na.", Body: "Ontvang de tracking- en uitzonderingsnotities die uw team nodig heeft voor voorraad- en klantcommunicatie."},
		},
		IndustriesTitle: "Logistiek die werkt zoals uw bedrijf werkt.", IndustriesBody: "Verschillende goederen vragen om verschillende controles, documenten en leveringsgesprekken. Het werk begint bij de beperking die voor uw operatie het belangrijkst is.",
		Industries: []publicIndustryItem{
			{Title: "E-commerce & retail", Body: "Houd aanvulling, bundels, marktplaatsvoorbereiding en winkelspecifieke verpakkingen geordend, van leverancier tot klant."},
			{Title: "Consumentengoederen", Body: "Coördineer productdetails, kwaliteitscontroles, lanceergereedheid en presentatie, van leverancier tot schap of voordeur."},
			{Title: "Industriële componenten", Body: "Werk vanuit specificaties, documentatie, ontvangsteisen en een helder plan voor de volgende productie- of serviceoverdracht."},
			{Title: "Urgente vracht", Body: "Geef prioriteit aan de eerstvolgende haalbare beweging en maak uitzonderingen vroeg zichtbaar wanneer de timing niet kan wachten."},
		},
		GuidesKicker: "KENNIS", GuidesTitle: "Kennis voor betere beslissingen.", GuidesBody: "Praktische uitleg over importvoorbereiding, Incoterms, een goed leveranciersbriefing, zee- versus luchtvracht en verpakkingscontrole.", GuidesLinks: []string{"Importchecklist", "Zee of lucht?", "Briefing voor leveranciers", "Verpakking voor directe levering"}, ReadMore: "Lees de gids", NoGuides: "Nederlandse versies van onze gidsen volgen.",
		FAQTitle: "Welke vragen spelen vóór de eerste overdracht?",
		FAQs: []publicFAQItem{
			{Question: "Kan ik beginnen met alleen een productlink?", Answer: "Ja. Een productlink, een foto of een korte specificatie is genoeg voor een eerste sourcinggesprek. Aantallen, bestemming en timing kunnen volgen zodra het plan duidelijker wordt."},
			{Question: "Kunt u sourcing en fulfilment combineren?", Answer: "Deze pagina presenteert sourcing, voorbereiding, transport, opslag en fulfilment als één verbonden werkwijze. Het definitieve bereik wordt in het verzendplan bevestigd."},
			{Question: "Helpt u zowel met zee- als met luchtvracht?", Answer: "Ja. Vertel ons wat er beweegt, hoe snel het moet aankomen en wat voor de zending het belangrijkst is. Wij bespreken de praktische route en de volgende overdracht."},
			{Question: "Verzorgt u de douaneafhandeling?", Answer: "Wij coördineren zendingsinformatie en documentoverdrachten. De verantwoordelijke douanevertegenwoordiger, de jurisdictie, de indeling en het formele bereik moeten zijn vastgesteld voordat een toezegging over afhandeling mogelijk is."},
			{Question: "Ondersteunt u opslag en fulfilment in Nederland?", Answer: "Vertel ons de eisen voor ontvangst, opslag, voorbereiding en vrijgave. Het beschikbare bereik moet in het plan worden bevestigd voordat er voorraad wordt verplaatst."},
			{Question: "Kan ik ook één enkele dienst aanvragen?", Answer: "Ja. U kunt beginnen met sourcing, transport, opslag, verpakking, fulfilment of een gecombineerd plan. In het formulier kiest u het startpunt."},
		},
		ContactKicker: "PLAN UW ZENDING", ContactTitle: "Wat moet er bewegen? Wij maken de route duidelijk.", ContactBody: "Deel product, vertrekpunt, bestemming en gewenste datum. Een FreightVanta-specialist beoordeelt de gegevens en reageert met de juiste volgende stap.", ContactButton: "Vraag een plan aan", FooterNote: "FreightVanta · Oplossingen · Sectoren · Kennis · Contact · Privacy · Juridische informatie.", PreviewNote: "Lokale preview · Deze pagina wordt niet geïndexeerd",
		MaintenanceTitle: "We zijn snel weer terug.", MaintenanceBody: "Deze website krijgt gepland onderhoud. Probeer het later opnieuw.", NotFoundTitle: "Deze route is niet gevonden.", NotFoundBody: "De pagina is mogelijk verplaatst of nog niet gepubliceerd in deze taal.", NotFoundButton: "Terug naar de homepage", ArticleBack: "Terug naar verzendgidsen", ArticleUpdated: "Bijgewerkt", ArticlePublished: "Gepubliceerd", ArticleReading: "Leestijd", ArticleMinute: "min", ArticleTags: "Onderwerpen", ArticleRelated: "Meer verzendgidsen",
	},
}
