package httpserver

import (
	"encoding/xml"
	"errors"
	"fmt"
	"net"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"czcms/internal/audit"
	"czcms/internal/catalog"

	"github.com/go-chi/chi/v5"
)

type sitemapXML struct {
	XMLName xml.Name     `xml:"urlset"`
	XMLNS   string       `xml:"xmlns,attr"`
	URLs    []sitemapURL `xml:"url"`
}

type sitemapURL struct {
	Loc     string `xml:"loc"`
	LastMod string `xml:"lastmod,omitempty"`
}

// siteSitemapPreview serves the same machine-readable file as a real site,
// but under the authenticated preview namespace. The local preview listeners
// forward /sitemap.xml here and keep the X-CZCMS-Local-Preview marker.
func (s *server) siteSitemapPreview(w http.ResponseWriter, r *http.Request) {
	site, err := s.Catalog.SiteByCode(r.Context(), chi.URLParam(r, "siteCode"))
	if errors.Is(err, catalog.ErrNotFound) {
		http.NotFound(w, r)
		return
	}
	if err != nil {
		http.Error(w, "service unavailable", http.StatusServiceUnavailable)
		return
	}
	s.renderSiteSitemap(w, r, site, true)
}

func (s *server) siteRobotsPreview(w http.ResponseWriter, r *http.Request) {
	site, err := s.Catalog.SiteByCode(r.Context(), chi.URLParam(r, "siteCode"))
	if errors.Is(err, catalog.ErrNotFound) {
		http.NotFound(w, r)
		return
	}
	if err != nil {
		http.Error(w, "service unavailable", http.StatusServiceUnavailable)
		return
	}
	s.renderSiteRobots(w, r, site, true)
}

// renderSiteSitemap dynamically builds one sitemap per site. It is kept
// independent from HTML rendering so large content tables can be streamed as
// a compact XML document without loading page bodies or template output.
func (s *server) renderSiteSitemap(w http.ResponseWriter, r *http.Request, site catalog.Site, preview bool) {
	if site.Status == "disabled" {
		s.trackSpiderRequest(r, site, preview, "sitemap.xml", publicSitePageData{}, "站点地图", http.StatusNotFound)
		http.NotFound(w, r)
		return
	}
	locales, err := s.Catalog.PublicSitemapLocales(r.Context(), site.ID)
	if err != nil {
		s.trackSpiderRequest(r, site, preview, "sitemap.xml", publicSitePageData{}, "站点地图", http.StatusServiceUnavailable)
		http.Error(w, "service unavailable", http.StatusServiceUnavailable)
		return
	}
	entries, err := s.Catalog.PublicSitemapEntries(r.Context(), site.ID)
	if err != nil {
		s.trackSpiderRequest(r, site, preview, "sitemap.xml", publicSitePageData{}, "站点地图", http.StatusServiceUnavailable)
		http.Error(w, "service unavailable", http.StatusServiceUnavailable)
		return
	}
	origin := s.sitemapOrigin(r, site, preview)
	urls := make([]sitemapURL, 0, len(locales)+len(entries))
	updated := site.UpdatedAt
	for _, locale := range locales {
		urls = append(urls, sitemapURL{Loc: origin + publicURL("", localeIf(len(locales) > 1, locale), ""), LastMod: sitemapLastMod(updated)})
	}
	for _, entry := range entries {
		urls = append(urls, sitemapURL{Loc: origin + publicURL("", localeIf(len(locales) > 1, entry.Locale), entry.Slug), LastMod: sitemapLastMod(entry.UpdatedAt)})
	}
	document, err := xml.MarshalIndent(sitemapXML{XMLNS: "http://www.sitemaps.org/schemas/sitemap/0.9", URLs: urls}, "", "  ")
	if err != nil {
		s.trackSpiderRequest(r, site, preview, "sitemap.xml", publicSitePageData{}, "站点地图", http.StatusInternalServerError)
		http.Error(w, "sitemap generation failed", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/xml; charset=utf-8")
	if preview || r.Header.Get("X-CZCMS-Local-Preview") == "1" {
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("X-Robots-Tag", "noindex, nofollow")
	} else {
		w.Header().Set("Cache-Control", "public, max-age=300, stale-while-revalidate=900")
	}
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(xml.Header))
	_, _ = w.Write(document)
	s.trackSpiderRequest(r, site, preview, "sitemap.xml", publicSitePageData{}, "站点地图", http.StatusOK)
}

func (s *server) renderSiteRobots(w http.ResponseWriter, r *http.Request, site catalog.Site, preview bool) {
	if site.Status == "disabled" {
		s.trackSpiderRequest(r, site, preview, "robots.txt", publicSitePageData{}, "robots.txt", http.StatusNotFound)
		http.NotFound(w, r)
		return
	}
	local := preview || r.Header.Get("X-CZCMS-Local-Preview") == "1"
	sitemapURL := s.sitemapOrigin(r, site, preview) + "/sitemap.xml"
	var body string
	if local {
		body = "# Generated by CZCMS for local preview.\nUser-agent: *\nDisallow: /\nSitemap: " + sitemapURL + "\n"
	} else {
		locales, localeErr := s.Catalog.PublicSitemapLocales(r.Context(), site.ID)
		noindexPages, pageErr := s.Catalog.PublicNoindexPagePaths(r.Context(), site.ID)
		settings, settingsErr := s.Catalog.GetSiteRobotsSettings(r.Context(), site.ID)
		if localeErr != nil || pageErr != nil || settingsErr != nil {
			s.trackSpiderRequest(r, site, preview, "robots.txt", publicSitePageData{}, "robots.txt", http.StatusServiceUnavailable)
			http.Error(w, "robots generation failed", http.StatusServiceUnavailable)
			return
		}
		var rules strings.Builder
		rules.WriteString("# Generated by CZCMS. Do not edit directly.\nUser-agent: *\nAllow: /\n")
		// Admin, APIs, uploaded media and form submissions are not public SEO
		// landing pages. The query-string rule avoids crawling dynamic variants
		// of otherwise canonical URLs without blocking the canonical route.
		for _, path := range []string{"/admin/", "/api/", "/login", "/setup", "/account/", "/preview/", "/media/", "/forms/", "/search", "/ajax/", "/*?"} {
			rules.WriteString("Disallow: ")
			rules.WriteString(path)
			rules.WriteByte('\n')
		}
		for _, extension := range []string{"jpg", "jpeg", "png", "gif", "webp", "avif", "svg"} {
			rules.WriteString("Disallow: /*.")
			rules.WriteString(extension)
			rules.WriteString("$\n")
		}
		for _, page := range noindexPages {
			rules.WriteString("Disallow: ")
			rules.WriteString(publicURL("", localeIf(len(locales) > 1, page.Locale), page.Slug))
			rules.WriteByte('\n')
		}
		rules.WriteString("Sitemap: ")
		rules.WriteString(sitemapURL)
		rules.WriteString("\n\n# Published pages with noindex policy, uploaded images and dynamic endpoints are automatically blocked.\n")
		if strings.TrimSpace(settings.CustomRules) != "" {
			rules.WriteString("\n# Site-specific rules managed in CZCMS SEO centre.\n")
			rules.WriteString(strings.TrimSpace(settings.CustomRules))
			rules.WriteByte('\n')
		}
		// Keep image search crawlers out of every image URL, including images
		// embedded in otherwise indexable HTML. This is independent of the
		// generic media path rule above and is understood by Google/Bing image
		// crawlers. Do not use the general Bingbot identity here: that would
		// accidentally block Bing's normal web crawler from HTML pages.
		rules.WriteString("\nUser-agent: Googlebot-Image\nDisallow: /\n\nUser-agent: msnbot-media\nDisallow: /\n")
		body = rules.String()
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	if local {
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("X-Robots-Tag", "noindex, nofollow")
	} else {
		w.Header().Set("Cache-Control", "public, max-age=300, stale-while-revalidate=900")
	}
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(body))
	s.trackSpiderRequest(r, site, preview, "robots.txt", publicSitePageData{}, "robots.txt", http.StatusOK)
}

func (s *server) sitemapOrigin(r *http.Request, site catalog.Site, preview bool) string {
	if r.Header.Get("X-CZCMS-Local-Preview") == "1" && site.LocalPort > 0 {
		return fmt.Sprintf("http://localhost:%d", site.LocalPort)
	}
	scheme := "https"
	if !s.Config.PublicHTTPS {
		scheme = "http"
	}
	if preview {
		host := sitemapPreviewHost(r.Host)
		if host == "" {
			host = site.PrimaryDomain
		}
		return scheme + "://" + host + "/preview/" + url.PathEscape(site.Code)
	}
	host := requestHostname(r.Host)
	if host == "" {
		host = site.PrimaryDomain
	}
	return scheme + "://" + host
}

func sitemapPreviewHost(value string) string {
	value = strings.TrimSpace(value)
	if value == "" || strings.ContainsAny(value, " \t\r\n/\\") {
		return ""
	}
	if host, port, err := net.SplitHostPort(value); err == nil {
		normalized := requestHostname(host)
		if normalized == "" || port == "" {
			return ""
		}
		return net.JoinHostPort(normalized, port)
	}
	return requestHostname(value)
}

func sitemapLastMod(value string) string {
	if value == "" {
		return ""
	}
	parsed, err := time.Parse(time.RFC3339Nano, value)
	if err != nil {
		return strings.TrimSpace(value)
	}
	return parsed.UTC().Format(time.RFC3339)
}

type seoSitemapSiteResponse struct {
	catalog.SitemapSiteStatus
	SitemapURL       string `json:"sitemap_url"`
	RobotsURL        string `json:"robots_url"`
	PublicSitemapURL string `json:"public_sitemap_url"`
	PublicRobotsURL  string `json:"public_robots_url"`
}

func (s *server) seoSitemaps(w http.ResponseWriter, r *http.Request) {
	session := sessionFromContext(r.Context())
	items, err := s.Catalog.ListSitemapSites(r.Context(), session.User.ID)
	if err != nil {
		writeJSONError(w, http.StatusInternalServerError, "读取站点地图状态失败")
		return
	}
	response := make([]seoSitemapSiteResponse, 0, len(items))
	var indexable, excluded, active int64
	for _, item := range items {
		local := fmt.Sprintf("http://localhost:%d", item.LocalPort)
		publicOrigin := ""
		if item.PrimaryDomain != "" {
			scheme := "https"
			if !s.Config.PublicHTTPS {
				scheme = "http"
			}
			publicOrigin = scheme + "://" + item.PrimaryDomain
		}
		if item.Status == "active" {
			active++
		}
		indexable += item.IndexablePageCount
		excluded += item.SinglePageExcludedCount
		response = append(response, seoSitemapSiteResponse{SitemapSiteStatus: item, SitemapURL: local + "/sitemap.xml", RobotsURL: local + "/robots.txt", PublicSitemapURL: publicOrigin + "/sitemap.xml", PublicRobotsURL: publicOrigin + "/robots.txt"})
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"sites":   response,
		"summary": map[string]int64{"site_count": int64(len(response)), "active_site_count": active, "indexable_page_count": indexable, "single_page_excluded_count": excluded},
	})
}

func (s *server) getSiteRobotsSettings(w http.ResponseWriter, r *http.Request) {
	siteID, ok := pathID(w, r, "siteID", "站点")
	if !ok {
		return
	}
	session := sessionFromContext(r.Context())
	if !s.canAccess(w, r, session.User.ID, "seo.manage", siteID, "*") {
		return
	}
	item, err := s.Catalog.GetSiteRobotsSettings(r.Context(), siteID)
	if errors.Is(err, catalog.ErrNotFound) {
		writeJSONError(w, http.StatusNotFound, "站点不存在")
		return
	}
	if err != nil {
		writeJSONError(w, http.StatusInternalServerError, "读取 robots 设置失败")
		return
	}
	writeJSON(w, http.StatusOK, item)
}

func (s *server) updateSiteRobotsSettings(w http.ResponseWriter, r *http.Request) {
	siteID, ok := pathID(w, r, "siteID", "站点")
	if !ok {
		return
	}
	session := sessionFromContext(r.Context())
	if !s.canAccess(w, r, session.User.ID, "seo.manage", siteID, "*") {
		return
	}
	var input struct {
		CustomRules string `json:"custom_rules"`
		Version     int64  `json:"version"`
	}
	// 24,000 Unicode characters may take up to 96 KiB as UTF-8, before the
	// surrounding JSON encoding. Validation in Catalog remains the actual
	// content limit; this transport limit only needs to leave room for it.
	if err := decodeJSON(w, r, &input, 128<<10); err != nil {
		return
	}
	item, err := s.Catalog.UpdateSiteRobotsSettings(r.Context(), siteID, session.User.ID, input.Version, input.CustomRules)
	if err != nil {
		status := http.StatusUnprocessableEntity
		switch {
		case errors.Is(err, catalog.ErrNotFound):
			status = http.StatusNotFound
		case errors.Is(err, catalog.ErrConflict):
			status = http.StatusConflict
		}
		writeJSONError(w, status, err.Error())
		return
	}
	s.audit(r, audit.Event{ActorUserID: &session.User.ID, Action: "seo.robots_updated", TargetType: "site_robots", TargetID: strconv.FormatInt(siteID, 10), Success: true, Metadata: map[string]any{"version": item.Version}})
	writeJSON(w, http.StatusOK, item)
}
