package httpserver

import (
	"encoding/xml"
	"errors"
	"fmt"
	"net"
	"net/http"
	"net/url"
	"strings"
	"time"

	"czcms/internal/catalog"

	"github.com/go-chi/chi/v5"
)

type sitemapXML struct {
	XMLName xml.Name     `xml:"urlset"`
	XMLNS   string       `xml:"xmlns,attr"`
	URLs    []sitemapURL `xml:"url"`
}

type sitemapURL struct {
	Loc     string `xml:"loc"`
	LastMod string `xml:"lastmod,omitempty"`
}

// siteSitemapPreview serves the same machine-readable file as a real site,
// but under the authenticated preview namespace. The local preview listeners
// forward /sitemap.xml here and keep the X-CZCMS-Local-Preview marker.
func (s *server) siteSitemapPreview(w http.ResponseWriter, r *http.Request) {
	site, err := s.Catalog.SiteByCode(r.Context(), chi.URLParam(r, "siteCode"))
	if errors.Is(err, catalog.ErrNotFound) {
		http.NotFound(w, r)
		return
	}
	if err != nil {
		http.Error(w, "service unavailable", http.StatusServiceUnavailable)
		return
	}
	s.renderSiteSitemap(w, r, site, true)
}

func (s *server) siteRobotsPreview(w http.ResponseWriter, r *http.Request) {
	site, err := s.Catalog.SiteByCode(r.Context(), chi.URLParam(r, "siteCode"))
	if errors.Is(err, catalog.ErrNotFound) {
		http.NotFound(w, r)
		return
	}
	if err != nil {
		http.Error(w, "service unavailable", http.StatusServiceUnavailable)
		return
	}
	s.renderSiteRobots(w, r, site, true)
}

// renderSiteSitemap dynamically builds one sitemap per site. It is kept
// independent from HTML rendering so large content tables can be streamed as
// a compact XML document without loading page bodies or template output.
func (s *server) renderSiteSitemap(w http.ResponseWriter, r *http.Request, site catalog.Site, preview bool) {
	if site.Status == "disabled" {
		http.NotFound(w, r)
		return
	}
	locales, err := s.Catalog.PublicSitemapLocales(r.Context(), site.ID)
	if err != nil {
		http.Error(w, "service unavailable", http.StatusServiceUnavailable)
		return
	}
	entries, err := s.Catalog.PublicSitemapEntries(r.Context(), site.ID)
	if err != nil {
		http.Error(w, "service unavailable", http.StatusServiceUnavailable)
		return
	}
	origin := s.sitemapOrigin(r, site, preview)
	urls := make([]sitemapURL, 0, len(locales)+len(entries))
	updated := site.UpdatedAt
	for _, locale := range locales {
		urls = append(urls, sitemapURL{Loc: origin + publicURL("", localeIf(len(locales) > 1, locale), ""), LastMod: sitemapLastMod(updated)})
	}
	for _, entry := range entries {
		urls = append(urls, sitemapURL{Loc: origin + publicURL("", localeIf(len(locales) > 1, entry.Locale), entry.Slug), LastMod: sitemapLastMod(entry.UpdatedAt)})
	}
	document, err := xml.MarshalIndent(sitemapXML{XMLNS: "http://www.sitemaps.org/schemas/sitemap/0.9", URLs: urls}, "", "  ")
	if err != nil {
		http.Error(w, "sitemap generation failed", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/xml; charset=utf-8")
	if preview || r.Header.Get("X-CZCMS-Local-Preview") == "1" {
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("X-Robots-Tag", "noindex, nofollow")
	} else {
		w.Header().Set("Cache-Control", "public, max-age=300, stale-while-revalidate=900")
	}
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(xml.Header))
	_, _ = w.Write(document)
}

func (s *server) renderSiteRobots(w http.ResponseWriter, r *http.Request, site catalog.Site, preview bool) {
	if site.Status == "disabled" {
		http.NotFound(w, r)
		return
	}
	local := preview || r.Header.Get("X-CZCMS-Local-Preview") == "1"
	sitemapURL := s.sitemapOrigin(r, site, preview) + "/sitemap.xml"
	var body string
	if local {
		body = "# Generated by CZCMS for local preview.\nUser-agent: *\nDisallow: /\nSitemap: " + sitemapURL + "\n"
	} else {
		body = "# Generated by CZCMS. Do not edit directly.\nUser-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /api/\nDisallow: /login\nDisallow: /setup\nDisallow: /account/\nDisallow: /preview/\nSitemap: " + sitemapURL + "\n\n# Single pages use page-level noindex and are excluded from Sitemap.\n"
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	if local {
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("X-Robots-Tag", "noindex, nofollow")
	} else {
		w.Header().Set("Cache-Control", "public, max-age=300, stale-while-revalidate=900")
	}
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(body))
}

func (s *server) sitemapOrigin(r *http.Request, site catalog.Site, preview bool) string {
	if r.Header.Get("X-CZCMS-Local-Preview") == "1" && site.LocalPort > 0 {
		return fmt.Sprintf("http://localhost:%d", site.LocalPort)
	}
	scheme := "https"
	if !s.Config.PublicHTTPS {
		scheme = "http"
	}
	if preview {
		host := sitemapPreviewHost(r.Host)
		if host == "" {
			host = site.PrimaryDomain
		}
		return scheme + "://" + host + "/preview/" + url.PathEscape(site.Code)
	}
	host := requestHostname(r.Host)
	if host == "" {
		host = site.PrimaryDomain
	}
	return scheme + "://" + host
}

func sitemapPreviewHost(value string) string {
	value = strings.TrimSpace(value)
	if value == "" || strings.ContainsAny(value, " \t\r\n/\\") {
		return ""
	}
	if host, port, err := net.SplitHostPort(value); err == nil {
		normalized := requestHostname(host)
		if normalized == "" || port == "" {
			return ""
		}
		return net.JoinHostPort(normalized, port)
	}
	return requestHostname(value)
}

func sitemapLastMod(value string) string {
	if value == "" {
		return ""
	}
	parsed, err := time.Parse(time.RFC3339Nano, value)
	if err != nil {
		return strings.TrimSpace(value)
	}
	return parsed.UTC().Format(time.RFC3339)
}

type seoSitemapSiteResponse struct {
	catalog.SitemapSiteStatus
	SitemapURL       string `json:"sitemap_url"`
	RobotsURL        string `json:"robots_url"`
	PublicSitemapURL string `json:"public_sitemap_url"`
	PublicRobotsURL  string `json:"public_robots_url"`
}

func (s *server) seoSitemaps(w http.ResponseWriter, r *http.Request) {
	session := sessionFromContext(r.Context())
	items, err := s.Catalog.ListSitemapSites(r.Context(), session.User.ID)
	if err != nil {
		writeJSONError(w, http.StatusInternalServerError, "读取站点地图状态失败")
		return
	}
	response := make([]seoSitemapSiteResponse, 0, len(items))
	var indexable, excluded, active int64
	for _, item := range items {
		local := fmt.Sprintf("http://localhost:%d", item.LocalPort)
		publicOrigin := ""
		if item.PrimaryDomain != "" {
			scheme := "https"
			if !s.Config.PublicHTTPS {
				scheme = "http"
			}
			publicOrigin = scheme + "://" + item.PrimaryDomain
		}
		if item.Status == "active" {
			active++
		}
		indexable += item.IndexablePageCount
		excluded += item.SinglePageExcludedCount
		response = append(response, seoSitemapSiteResponse{SitemapSiteStatus: item, SitemapURL: local + "/sitemap.xml", RobotsURL: local + "/robots.txt", PublicSitemapURL: publicOrigin + "/sitemap.xml", PublicRobotsURL: publicOrigin + "/robots.txt"})
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"sites":   response,
		"summary": map[string]int64{"site_count": int64(len(response)), "active_site_count": active, "indexable_page_count": indexable, "single_page_excluded_count": excluded},
	})
}
